query($filters: JSON, $where: JSON) {
  Contact {
    ContactFind(filter: $filters) {
      edges {
        node {
          id
          Type
          CellPhone
          WorkPhone
          SubscriptionStatus
          Organization
          LastName
          Job
          Department
          Type
          Gender
          FullName
          FirstName
          Fax
          Email
          Description
          BirthDate
          Owner
          ReportsTo
          Assistant
          AsstPhone
          orgId
          AttachmentId
          contactPic
          accesskeyId
          accesskey {
            id
            accesskey
            accesssecret
            expiresat
            createdDate
            createdBy
            modifiedDate
            modifiedBy
            userId
          }
          _Comment {
            id
            Notes
            createdDate
            createdBy
            modifiedDate
            modifiedBy
            AttachmentId
          }
          _CurrentAddress {
            AddressLine
            City
            Country
            LatLng {
              lat
              lng
            }
            PostalCode
            State
            id
            createdDate
            createdBy
            modifiedDate
            modifiedBy
          }
          createdDate
          createdBy
          modifiedDate
          modifiedBy
        }
      }
    }
    ContactCount(where: $where)
  }
}
