query ($filters: JSON, $where: JSON) {
      OfferCode {
        OfferCodeFind(filter: $filters) {
          edges {
            node {
              codeTitle
          createdAt
          currentUsageCount
          description
          eventCode
          eventName
          hasValidity
          id
          isActive
          isMaxOfferValueCheck
          isPercent
          maxApplicableAmount
          maxUsageCount
          minApplicableOrderAmount
          offerValue
          validTill
          EventId
          getEvent {
                AutoUpdateSEOElements
            SEOTitle
            SEOKeywords
            SEODesc
            CancellationPolicy
            CostCenter
            Currency
            Description
            EndDate
            EventCountdown
            EventManager
            IsOnlineEvent
            LegalEntity
            MaxNoRegistrations
            Message
            MinDaysCancelling
            Organizer
            Privacy
            Project
            ProjectCode
            SalesforceEventId
            SeatReservation
            SessionTimingConflict
            ShowRemainingTickets
            StartDate
            Status
            SyncStatus
            Tags
            Timezone
            Title
            UpdateQuestion
            VenueName
            ShowAttendeeForm
            CapturePoint
            RegistrationSiteTemplate
            isRefundable
            WebinarLink
            JoiningInstruction
            showTimezone
            UniqLink
            BusinessType
            Duration
            BufferBefore
            BufferAfter
            LocationType
            ScheduledType
            RollingDays
            AvailableEndHour
            Frequency
            MinimumSchedulingNotice
            AvailableStartHour
            Type
            NotifyOrganizer
            SendCalendar
            id
            orgId
            createdDate
            createdBy
            modifiedDate
            modifiedBy
            Logo
            Banner
            Images
            Thumbnail
            Other
            ParentId
            MySpeakers
            _VenueAddress {
                  AddressLine
              City
              Country
              LatLng {
                    lat
                lng
        
              }
              PostalCode
              State
              id
              createdDate
              createdBy
              modifiedDate
              modifiedBy
        
            }
            _Survey {
                  ControlType
              DisplayOrder
              Label
              Options
              Question
              SFQuestionId
              SyncStatus
              isRegistrationField
              isRequired
              isShowField
              TicketName
              showAttendeeField
              isAttendeeField
              id
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              TicketIds
        
            }
            _RegistrationForm {
                  ControlType
              DisplayOrder
              Label
              Options
              Question
              SFQuestionId
              SyncStatus
              isRegistrationField
              isRequired
              isShowField
              TicketName
              showAttendeeField
              isAttendeeField
              id
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              TicketIds
        
            }
            _Comments {
                  id
              Notes
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              AttachmentId
        
            }
            _EventLogistic {
                  id
              Room
              RoomSetup
              RoomCapacity
              MaxRegistrant
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              SessionId
        
            }
            TemplateId
            _otherReferanceId {
                  ServiceId
              ReferenceId
              id
              createdDate
              createdBy
              modifiedDate
              modifiedBy
        
            }
            _sectionHeading {
                  session
              registrationTypes
              speakers
              registrationbtn
              registrationquestionsectionlabel
              sessionsectionlabel
              venuelabel
              datetimelabel
              ticketlabel
              ticketsectionlabel
              showimagegallery
              showeventreviews
              review
              gallery
              animation
              id
              createdDate
              createdBy
              modifiedDate
              modifiedBy
        
            }
            LayoutId
    
          }
          MemberId
          createdDate
          createdBy
          modifiedDate
          modifiedBy
    
        }

      }

    }
    OfferCodeCount(where: $where)
  }
}