query ($filters: JSON) {
  Event {
    EventFind(filter: $filters) {
      edges {
        node {
          id
          BufferBefore
          BufferAfter
          LocationType
          ScheduledType
          RollingDays
          Frequency
          _RegistrationForm{
            id
            Label
            ControlType
            DisplayOrder
            isShowField
            isAttendeeField
            isRequired
            Question
          }
        }
      }
    }
  }
}