query($filters: JSON, $badgeFilter: JSON, $eventId: String) {
  Event {
    EventFind(filter: $filters) {
      edges {
        node {
          id
          createdDate
          createdBy
          SendCalendar
          NotifyOrganizer
          WebinarLink
          JoiningInstruction
          showTimezone
          UniqLink
          isRefundable
          allowChat
          chatChannel
          RegistrationSiteTemplate
          ShowAttendeeForm
          CapturePoint
          AutoUpdateSEOElements
          SEOTitle
          SEOKeywords
          SEODesc
          CancellationPolicy
          CostCenter
          Currency
          Description
          EndDate
          EventCountdown
          EventManager
          IsOnlineEvent
          LegalEntity
          MaxNoRegistrations
          Message
          MinDaysCancelling
          Organizer
          Privacy
          Project
          ProjectCode
          SalesforceEventId
          LayoutId
          SeatReservation
          SessionTimingConflict
          ShowRemainingTickets
          printBadgeOnCheckIn
          StartDate
          Status
          Logo
          LiveStreamBanner
          Banner
          Images
          Other
          SyncStatus
          Tags
          Timezone
          Title
          UpdateQuestion
          VenueName
          BusinessType
          Duration
          BufferBefore
          BufferAfter
          LocationType
          ScheduledType
          RollingDays
          Frequency
          MinimumSchedulingNotice
          AvailableEndHour
          MySpeakers
          _VenueAddress {
            id
            State
            PostalCode
            LatLng {
              lat
              lng
            }
            Country
            City
            AddressLine
            createdDate
            createdBy
            modifiedDate
            modifiedBy
          }
          _sectionHeading {
            id
            registrationquestionsectionlabel
            sessionsectionlabel
            venuelabel
            datetimelabel
            ticketlabel
            ticketsectionlabel
            showimagegallery
            showeventreviews
            review
            gallery
            session
            registrationTypes
            speakers
            registrationbtn
            animation
            createdDate
            createdBy
            modifiedDate
            modifiedBy
          }
        }
      }
    }
    EventGetEventSummery(id: $eventId)
  }
  Badge {
    BadgeFind(filter: $badgeFilter) {
      edges {
        node {
          id
          Category
          Name
          Template
        }
      }
    }
  }
}
