query ($filters: JSON, $where: JSON) {
    EmailAnalytic {
        EmailAnalyticFind(filter: $filters) {
            edges {
                node {
                    id
                    Open
                    Sent
                    Bounce
                    isRegistered      
                    Deleted
                    Delivered
                    Click  
                    SpamReport      
                    Unsubscribed
                    orgId
                    ContactId
                    getContact {
                        id
                        LastName
                        FullName
                        FirstName
                        Email
                        __typename
                    }
                    CRMActivityId
                    createdDate
                    createdBy
                    modifiedDate
                    event {
                        id
                        Title
                        __typename
                    }
                    getCRMActivityId{ 
                        Title
                    }      
                    modifiedBy
                    __typename
                }
                __typename
            }
            __typename
        }
        EmailAnalyticCount(where: $where)
        __typename
    }
}