query ($filters: JSON, $where: JSON) { 
    OfferCode{ 
        OfferCodeFind(filter: $filters) { 
            edges { 
                node { 
                    id 
                    codeTitle 
                    offerValue 
                    hasValidity 
                    validTill 
                    isActive 
                    isMaxOfferValueCheck 
                    isPercent 
                    createdDate 
                    createdBy 
                    modifiedDate
                    maxApplicableAmount
                    description
                    minApplicableOrderAmount
                    maxUsageCount 
                    __typename 
                } 
                __typename 
            }
        __typename 
        } 
        OfferCodeCount(where: $where) 
        __typename
    } 
}