query ($filters: JSON, $where: JSON) { 
    Ticket { 
        TicketFind(filter: $filters) { 
            edges { 
                node { 
                    ValidateQty 
                    TicketCount 
                    AvailableCount 
                    CheckGroupDiscount
                    DisplayOrder 
                    EndDate 
                    SyncStatus 
                    Code 
                    StartDate 
                    Currency 
                    Amount 
                    Type 
                    id 
                    Description 
                    Group 
                    Attendee 
                    createdDate 
                    createdBy 
                    modifiedDate 
                    __typename 
                } 
                __typename 
            } 
            __typename 
        } 
        TicketCount(where: $where) 
        __typename 
    } 
}