query($filters: JSON, $where: JSON) {
  Attendee {
    AttendeeFind(filter: $filters) {
      edges {
        node {
          FirstName
          Status
          FullName
          TicketName
          TicketAmount
          categoryId
          TicketId
          SeatNumber
          CompanyName
          CheckIn
          LastName
          Email
          Phone
          id
          createdDate
          createdBy
          modifiedDate
          BookingDate
          _CurrentAddress {
            AddressLine
            City
            Country
            PostalCode
            State
          }
          regType {
            Name
          }
          registration {
            id
            FullName
          }
          attendeeTicket {
            id
            Code
          }
          __typename
        }
        __typename
      }
      __typename
    }
    AttendeeCount(where: $where)
    __typename
  }
}