query($filters: JSON, $ticketFilters: JSON, $sessionFilters: JSON) {
  Location {
    LocationFind(filter: $filters) {
      edges {
        node {
          id
          Name
          Default
        }
      }
    }
  }
  Ticket {
    TicketFind(filter: $ticketFilters) {
      edges {
        node {
          id
          Code
        }
      }
    }
  }
  Session {
    SessionFind(filter: $sessionFilters) {
      edges {
        node {
          id
          StartTime
          EndTime
        }
      }
    }
  }
  OrganizationInfo {
    OrganizationInfoFind(filter: $filters) {
      edges {
        node {
          id
          weekDay
        }
      }
    }
  }
}
