query($filters: JSON, $slotFilters: JSON) {
  OrganizationInfo {
    OrganizationInfoFind(filter: $filters) {
      edges {
        node {
          id
          Currency
        }
      }
    }
  }
  GeneralConfiguration {
    GeneralConfigurationFind(filter: $slotFilters) {
      edges {
        node {
          id
          value
          key
          type
        }
      }
    }
  }
}