query($filters: JSON, $slotFilters: JSON, $inPersonMeetingFilters: JSON) {
  OrganizationInfo {
    OrganizationInfoFind(filter: $filters) {
      edges {
        node {
          id
          Currency
          Image
          weekDay
          AvailableEndHour
          AvailableStartHour
        }
      }
    }
  }
  GeneralConfiguration {
    GeneralConfigurationFind(filter: $slotFilters) {
      edges {
        node {
          id
          value
          key
          type
        }
      }
    }
  }
  Location {
    LocationFind(filter: $inPersonMeetingFilters) {
      edges {
        node {
          id
          Name
          Default
        }
      }
    }
  }
}
