query($filters: JSON) {
  Registration {
    RegistrationFind(filter: $filters) {
      edges {
        node {
          id
          Email
          EventName
          EventId
          FirstName
          TotalAmount
          TicketQuantity
          CompanyName
          FullName
          LastName
          _Comment {
            Notes
            id
          }
          Category
          _QuestionResponse {
            Answer
            id
          }
          PaymentMethod
          CheckIn
          Phone
          RegistrationId
          Status
          createdDate
          EventList {
            _VenueAddress {
              id
              City
              State
              PostalCode
              AddressLine
              Country
            }
          }
        }
      }
    }
  }
}
