query($filters: JSON) {
  RegistrationType {
    RegistrationTypeFind(filter: $filters) {
      edges {
        node {
            id
            Name
            isDefault
            ColorCode
            MaxQuantityAllowed
            DisplayOrder
            EventId
            AllowMultiple
        }
      }
    }
  }
}
