query($filters: JSON, $where: JSON) {
  Registration {
    RegistrationFind(filter: $filters) {
      edges {
        node {
          id
          Email
          EventName
          EventId
          FirstName
          TotalAmount
          TicketQuantity
          CompanyName
          FullName
          LastName
          SessionId
          _Comment {
            Notes
            id
          }
          Category
          _QuestionResponse {
            Answer
            id
          }
          PaymentMethod
          CheckIn
          Phone
          TicketId
          RegistrationId
          Status
          createdDate
          ZoomLink
          EventList {
            _VenueAddress {
              id
              City
              State
              PostalCode
              AddressLine
              Country
            }
          }
          _CurrentAddress{
            id
            AddressLine
            City
            Country
            PostalCode
            State
          }
        }
      }
    }
    RegistrationCount(where: $where)
  }
}
