query($filters: JSON) {
  Registration {
    RegistrationFind(filter: $filters) {
      edges {
        node {
          id
          Email
          EventName
          EventId
          FirstName
          SubTotal
          TotalAmount
          Discount
          Currency
          TicketQuantity
          CompanyName
          SessionId
          FullName
          LastName
          _Comment {
            Notes
            id
          }
          Category
          _QuestionResponse {
            Answer
            id
            QuestionId
          }
          PaymentMethod
          CheckIn
          Phone
          RegistrationId
          Status
          createdDate
          _CurrentAddress {
            id
            City
            State
            PostalCode
            AddressLine
            Country
          }
          _Refund {
            id
            TransactionType
            TransactionID
            RefundStatus
            RefundRequest
            RefundMethod
            Reason
            Comments
            Amount
            RefundInitiatedDate
            createdDate
            createdBy
            modifiedDate
            modifiedBy
          }
          _CustomerPayment {
            brand
            card_holder_name
            last4
            token
            processorAuthorizationCode
            id
            createdDate
            createdBy
            modifiedDate
            modifiedBy
          }
        }
      }
    }
  }
}
