query($filters: JSON) {
  GeneralConfiguration {
    GeneralConfigurationFind(filter: $filters) {
      edges {
        node {
          id
          value
          key
        }
      }
    }
  }
}
