query($filters: JSON, $where: JSON) {
  GeneralConfiguration {
    GeneralConfigurationFind(filter: $filters) {
      edges {
        node {
          id
          value
          key
          type
          name
        }
      }
    }
    GeneralConfigurationCount(where: $where)
  }
}
