query ($filters: JSON) { 
    Ticket { 
        TicketFind(filter: $filters) { 
            edges { 
                node { 
                    Amount
                    Code 
                    id 
                } 
            } 
        } 
    } 
}