<template>
  <v-text-field
    v-model="filterRule.value"
    :label="$t('Common.EnterValue')"
    type="number"
    outlined
    dense
    @keyup.enter="onFilterInput"
  ></v-text-field>
</template>
