import eventNames from '../gql/eventNames.gql'
import discountCodes from '../gql/discountCodes.gql'
import { getData } from '../rest'

export default {
  dataSource: {
    Type: 'List',
    URL: 'Offercode',
  },
  general: {
    caption: 'OfferCodes',
    name: 'OfferCode',
  },
  views: {
    'Discount Codes': {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: true,
        hideSearch: false,
      },
      itemTitle: 'Discount Code',
      defaultSort: 'createdDate DESC',
      fields: {
        currentUsageCount: {
          displayOrder: 9,
          caption: 'Current Usage Count',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '220px',
          type: 'number',
          inlineEdit: false,
          newForm: false,
          editForm: false,
        },
        codeTitle: {
          form: {
            caption: 'Code *',
            displayOrder: 1,
          },
          displayOrder: 1,
          caption: 'Code',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
          cssClasses: 'col-12 col-md-12',
          inlineEdit: true,
          newForm: true,
          editForm: true,
          rules: [
            (v) => {
              return !!v || 'Please fill out this field'
            },
          ],
        },
        Description: {
          form: {
            caption: 'Description',
            displayOrder: 2,
          },
          displayOrder: 2,
          caption: 'Description',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'richtext',
          hidden: true,
          cssClasses: 'col-12 col-md-12',
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        isActive: {
          form: {
            caption: 'Is Active',
            displayOrder: 4,
          },
          displayOrder: 4,
          caption: 'IsActive',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '120px',
          type: 'checkbox',
          cssClasses: 'col-6 col-md-6',
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        isPercent: {
          form: {
            caption: 'Is percent',
            displayOrder: 3,
          },
          displayOrder: 3,
          caption: 'IsPercent',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'checkbox',
          cssClasses: 'col-6 col-md-6',
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        validTill: {
          form: {
            caption: 'Valid Till',
            displayOrder: 7,
          },
          displayOrder: 7,
          caption: 'Valid Till',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'date',
          cssClasses: 'col-6 col-md-6',
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        offerValue: {
          form: {
            caption: 'Offer Value *',
            displayOrder: 5,
          },
          displayOrder: 5,
          caption: 'Offer Value',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'number',
          cssClasses: 'col-6 col-md-6',
          inlineEdit: true,
          newForm: true,
          editForm: true,
          minimumValue: '1',
          rules: [
            (v) => {
              return !!v || 'Please fillout this field'
            },
          ],
        },
        minApplicableOrderAmount: {
          form: {
            caption: 'Min Applicable Order Amount',
            displayOrder: 6,
          },
          displayOrder: 6,
          caption: 'Min Applicable Amount',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '220px',
          type: 'number',
          cssClasses: 'col-6 col-md-6',
          inlineEdit: true,
          newForm: true,
          editForm: true,
          minimumValue: '1',
        },
        maxApplicableAmount: {
          form: {
            caption: 'Max Applicable Amount',
            displayOrder: 8,
          },
          displayOrder: 8,
          caption: 'Max Applicable Amount',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'number',
          cssClasses: 'col-6 col-md-6',
          inlineEdit: true,
          newForm: true,
          editForm: true,
          hidden: true,
          minimumValue: '1',
        },
        maxUsageCount: {
          form: {
            caption: 'Max Usage Count',
            displayOrder: 9,
          },
          displayOrder: 8,
          caption: 'Max Usage Count',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'number',
          cssClasses: 'col-6 col-md-6',
          inlineEdit: true,
          newForm: true,
          editForm: true,
          minimumValue: '1',
        },
        createdDate: {
          displayOrder: 10,
          caption: 'Created Date',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '250px',
          type: 'date',
          cssClasses: 'col-12 col-md-12',
          inlineEdit: false,
          newForm: false,
          editForm: false,
        },
        EventId: {
          form: {
            caption: 'Event',
            displayOrder: 10,
          },
          caption: 'Event',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'lookup',
          cssClasses: 'col-6 col-md-6',
          hidden: true,
          inlineEdit: true,
          newForm: true,
          editForm: true,
          dataSource: {
            query: eventNames,
            defaultSort: 'createdDate DESC',
            type: 'graphql',
            model: 'Event',
            itemText: 'Title',
            itemValue: 'id',
            filter(data) {
              return {
                and: [
                  { EndDate: { gte: new Date() } },
                  { Status: `Open for registration` },
                ],
              }
            },
          },
        },
      },
      template: {
        name: 'discount-grid',
        context: {
          basePath: '/discountcodes',
        },
      },
      dataSource: {
        query: discountCodes,
        defaultSort: 'createdDate DESC',
        type: 'graphql',
        model: 'OfferCode',
      },
      title: 'Discount Codes',
      model: 'OfferCode',
    },
    discountMembers: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: false,
        hideSearch: true,
      },
      fields: {
        FirstName: {
          displayOrder: 2,
          caption: 'First Name',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '220px',
          type: 'string',
        },
        LastName: {
          displayOrder: 3,
          caption: 'Last Name',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Email: {
          displayOrder: 4,
          caption: 'Email',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '120px',
          type: 'string',
        },
        BusinessNumber: {
          displayOrder: 5,
          caption: 'Business Number',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        createdDate: {
          displayOrder: 6,
          caption: 'Created Date',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'datetime',
        },
        Action: {
          displayOrder: 7,
          caption: 'Action',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
        },
      },
      template: {
        name: '',
        context: {
          basePath: '/discountcodes',
        },
      },
      dataSource: {
        type: 'rest',
        getData: (ctx) =>
          getData(`/OfferCodes/${ctx.$route.params.id}/getMember`),
      },
      hidden: true,
      title: 'discountMembers',
      type: 'list',
    },
  },
}
