query($filters: JSON, $where: JSON) {
  Badge {
    BadgeFind(filter: $filters) {
      edges {
        node {
          id
          Type
          DisplayOrder
          Size
          Name
          Category
          Default
          Template
          orgId
          EventId
          event {
            id
            SendCalendar
            NotifyOrganizer
            WebinarLink
            JoiningInstruction
            showTimezone
            UniqLink
            isRefundable
            RegistrationSiteTemplate
            ShowAttendeeForm
            CapturePoint
            AutoUpdateSEOElements
            SEOTitle
            SEOKeywords
            SEODesc
            CancellationPolicy
            CostCenter
            Currency
            Description
            EndDate
            EventCountdown
            EventManager
            IsOnlineEvent
            LegalEntity
            MaxNoRegistrations
            Message
            MinDaysCancelling
            Organizer
            Privacy
            Project
            ProjectCode
            SalesforceEventId
            SeatReservation
            SessionTimingConflict
            ShowRemainingTickets
            StartDate
            Status
            SyncStatus
            Tags
            Timezone
            Title
            UpdateQuestion
            VenueName
            BusinessType
            Duration
            BufferBefore
            BufferAfter
            LocationType
            ScheduledType
            RollingDays
            Frequency
            MinimumSchedulingNotice
            AvailableEndHour
            AvailableStartHour
            Type
            orgId
            createdDate
            createdBy
            modifiedDate
            modifiedBy
            Logo
            Banner
            Images
            Thumbnail
            Other
            ParentId
            MySpeakers
            _VenueAddress {
              AddressLine
              City
              Country
              LatLng {
                lat
                lng
                __typename
              }
              PostalCode
              State
              id
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              __typename
            }
            _RegistrationForm {
              id
              TicketName
              showAttendeeField
              isAttendeeField
              ControlType
              DisplayOrder
              Label
              Options
              Question
              SFQuestionId
              SyncStatus
              isRegistrationField
              isRequired
              isShowField
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              TicketIds
              __typename
            }
            _Survey {
              id
              TicketName
              showAttendeeField
              isAttendeeField
              ControlType
              DisplayOrder
              Label
              Options
              Question
              SFQuestionId
              SyncStatus
              isRegistrationField
              isRequired
              isShowField
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              TicketIds
              __typename
            }
            _Comments {
              id
              Notes
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              AttachmentId
              __typename
            }
            _EventLogistic {
              id
              Room
              RoomSetup
              RoomCapacity
              MaxRegistrant
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              SessionId
              __typename
            }
            BadgeId
            TemplateId
            _otherReferanceId {
              id
              ReferenceId
              ServiceId
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              __typename
            }
            _sectionHeading {
              id
              registrationquestionsectionlabel
              sessionsectionlabel
              venuelabel
              datetimelabel
              ticketlabel
              ticketsectionlabel
              showimagegallery
              showeventreviews
              review
              gallery
              session
              registrationTypes
              speakers
              registrationbtn
              animation
              createdDate
              createdBy
              modifiedDate
              modifiedBy
              __typename
            }
            LayoutId
            __typename
          }
          createdDate
          createdBy
          modifiedDate
          modifiedBy
          __typename
        }
        __typename
      }
      __typename
    }
    BadgeCount(where: $where)
    __typename
  }
}
