query($filters: JSON) {
  PrintedTicketTemplate {
    PrintedTicketTemplateFind(filter: $filters) {
      edges {
        node {
          id
          Size
          Name
          ThumbnailUrl
          isDefault
          Template
          createdDate
          createdBy
          modifiedDate
          modifiedBy
          eventId
        }
      }
    }
  }
}
