export const appList = (store) => [
  {
    name: 'event',
    label: 'Common.EventApp',
    css: 'fa fa-video fs-36 red--text',
    type: 'route',
    route: '/apps/event/list/Event/live-and-draft-event',
    roles: ['$orguser', '$orgowner', 'EventAdmin', 'EventManager'],
  },
  {
    name: 'admin',
    label: 'Common.AdminApp',
    css: 'fa fa-cogs fs-36 primary--text',
    type: 'route',
    route: `/apps/admin/organization/${
      store.state.currentOrgInfo && store.state.currentOrgInfo.id
    }`,
    roles: ['EventAdmin', '$orgowner'],
  },
  {
    name: 'HelpCenter',
    label: 'Common.HelpCenterMap',
    css: 'fa fa-help-circle fs-36 success--text',
    type: 'route',
    route: '/apps/help-center',
    roles: ['$authenticated'],
  },

  {
    name: 'Survey',
    label: 'Common.SurveyApp',
    css: 'fa fa-check-circle fs-36 primary--text',
    type: 'url',
    href: 'https://survey.bitpod.io/',
    roles: ['$orguser'],
  },
  {
    name: 'seatmap',
    label: 'Common.SeatMapNo',
    css: 'fa fa-grid-alt fs-36 success--text',
    type: 'route',
    route: '/apps/seatmap/list/seatmaps/seatmaps',
    roles: ['$orguser'],
  },
  {
    name: 'integration',
    label: 'Common.Integration',
    css: 'fa fa fa-link1 fs-36 warning--text',
    type: 'route',
    route: '/apps/integration/list/integration/integration',
    roles: ['$developer', '$orgowner', 'EventAdmin', 'Events', 'SFIntegration'],
  },
  {
    name: 'member',
    label: 'Common.CommunityApp',
    css: 'fa fa-grow fs-36 red--text',
    type: 'route',
    route: '/apps/member/list/Member/Members',
    roles: ['$orguser', '$orgowner', 'EventAdmin', 'EventManager'],
  },
  {
    name: 'E-Sign',
    label: 'Common.ESignature',
    css: 'mdi mdi-file-document-edit-outline fs-36 warning--text',
    type: 'route',
    route: '/apps/eSign/list/eSignRequest/eSign',
    roles: [],
  },
  {
    name: 'UserProfile',
    label: 'Common.UserProfileApp',
    css: 'fa fa-user fs-36 success--text',
    type: 'route',
    route: '/apps/userprofile/user-profile',
    roles: ['$authenticated'],
  },
]
