import memberList from '../gql/memberList.gql'
import subscription from '../gql/subscription.gql'
import registrationStatusOptions from '~/config/apps/event/gql/registrationStatusOptions.gql'
import contactList from '~/config/apps/event/gql/contactList.gql'
import memberTasks from '~/config/apps/event/gql/eventTasks.gql'
import { getCustomData } from '~/config/apps/event/rest'
// import { getCustomData } from '~/config/apps/event/rest'

export default {
  views: {
    Members: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: false,
        hideSearch: false,
      },
      itemTitle: 'Common.Members',
      fields: {
        FirstName: {
          form: {
            caption: 'Common.FirstName',
            displayOrder: 1,
          },
          displayOrder: 2,
          caption: 'Common.FirstNameCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-12 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.FirstNameRequired')
            },
          ],
        },
        LastName: {
          form: {
            caption: 'Common.LastName',
            displayOrder: 2,
          },
          displayOrder: 3,
          caption: 'Common.LastNameCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-12 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.LastNameRequired')
            },
          ],
        },
        Email: {
          form: {
            caption: 'Common.Email',
            displayOrder: 3,
          },
          displayOrder: 4,
          caption: 'Common.EmailCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          cssClasses: 'col-12 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.EmailRequired')
            },
            function (value, data) {
              return /.+@.+\..+/.test(value) || 'E-mail must be valid'
            },
          ],
        },
        BusinessNumber: {
          form: {
            caption: 'Common.PhoneRequired',
            displayOrder: 4,
          },
          displayOrder: 5,
          caption: 'Common.BusinessNumber',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '165px',
          type: 'string',
          cssClasses: 'col-12 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.PhoneRequired')
            },
            function (value, data) {
              return /^[0-9]\d*$|^$/.test(value) || 'Number must be valid'
            },
          ],
        },
        createdDate: {
          displayOrder: 6,
          caption: 'Common.CreatedDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'date',
          newForm: false,
          editForm: false,
          customExport: (startDate) => {
            if (startDate) {
              const tempDate = new Date(startDate)
              return (
                tempDate.toLocaleDateString() +
                ' ' +
                tempDate.toLocaleTimeString()
              )
            }
            return ''
          },
        },
        createdBy: {
          displayOrder: 7,
          caption: 'Common.CreatedBy',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          newForm: false,
          editForm: false,
        },
        Tags: {
          form: {
            caption: 'Common.Tags',
            displayOrder: 5,
          },
          caption: 'Common.Tags',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'tags',
          hidden: true,
          newForm: true,
          editForm: true,
          cssClasses: 'col-12 col-md-12',
        },
        '_BillingAddress.AddressLine': {
          form: {
            caption: 'Common.Address',
            displayOrder: 6,
          },
          caption: 'Common.Address',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: true,
          editForm: true,
          cssClasses: 'col-12 col-md-12',
        },
        '_BillingAddress.City': {
          form: {
            caption: 'Common.City',
            displayOrder: 7,
          },
          caption: 'Common.City',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: true,
          editForm: true,
          cssClasses: 'col-12 col-md-6',
        },
        '_BillingAddress.State': {
          form: {
            caption: 'Common.State',
            displayOrder: 8,
          },
          caption: 'Common.State',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: true,
          editForm: true,
          cssClasses: 'col-12 col-md-6',
        },
        '_BillingAddress.PostalCode': {
          form: {
            caption: 'Common.Zip',
            displayOrder: 9,
          },
          caption: 'Common.Zip',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: true,
          editForm: true,
          cssClasses: 'col-12 col-md-6',
        },
        '_BillingAddress.Country': {
          form: {
            caption: 'Common.Country',
            displayOrder: 10,
          },
          caption: 'Common.Country',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: true,
          editForm: true,
          cssClasses: 'col-12 col-md-6',
        },
        Description: {
          form: {
            caption: 'Common.Description',
            displayOrder: 11,
          },
          caption: 'Common.Description',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: true,
          editForm: true,
          cssClasses: 'col-12 col-md-12',
        },
      },
      template: {
        name: 'member-grid',
        context: {
          basePath: '/member',
        },
      },
      dataSource: {
        singularEntity: 'Common.Members',
        pluralEntity: 'Drawer.Members',
        query: memberList,
        type: 'graphql',
        model: 'Customer',
        defaultSort: 'createdDate DESC',
      },
      title: 'Drawer.Members',
      defaultSort: 'createdDate DESC',
    },
    memberSubscription: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: false,
        hideFilter: false,
        hideSearch: true,
      },
      itemTitle: 'Subscription',
      hidden: true,
      fields: {
        SystemOrgName: {
          displayOrder: 2,
          caption: 'Subscription',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-12 col-md-12',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        Unit: {
          displayOrder: 5,
          caption: 'Unit',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'number',
          cssClasses: 'col-6 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        EndDate: {
          displayOrder: 3,
          caption: 'EndDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'date',
          cssClasses: 'col-6 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        BankTransactionNumber: {
          displayOrder: 4,
          caption: 'BankTransactionNumber',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-6 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
      },
      template: {
        name: 'organizationSubscription-grid',
        context: {
          basePath: '/organization',
        },
        actions: {
          edit: {
            hidden: true,
          },
          exportCsv: {
            hidden: true,
          },
        },
      },
      dataSource: {
        singularEntity: 'Subsciption',
        pluralEntity: 'Subsciptions',
        query: subscription,
        defaultSort: 'createdDate DESC',
        type: 'graphql',
        model: 'ProductSubscription',
        filter(ctx) {
          return {
            where: { CustomerId: this.$route.params.id },
          }
        },
      },
      title: 'Subscription',
      type: 'list',
    },
    memberTasks: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: false,
        hideFilter: false,
        hideSearch: true,
      },
      itemTitle: 'Common.Task',
      hidden: true,
      fields: {
        Title: {
          displayOrder: 2,
          caption: 'Common.TitleCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-12 col-md-12',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        Category: {
          displayOrder: 5,
          caption: 'Common.Category',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'lookup',
          cssClasses: 'col-6 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        Status: {
          displayOrder: 3,
          caption: 'Common.Status',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'lookup',
          cssClasses: 'col-6 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        Action: {
          displayOrder: 4,
          caption: 'Common.WaitFor',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'lookup',
          cssClasses: 'col-6 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        SurveyId: {
          cssClasses: 'col-12 col-md-12',
          caption: 'Common.SurveyList',
          searchEnable: true,
          sortEnable: true,
          type: 'string',
          hidden: true,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        TemplateId: {
          cssClasses: 'col-12 col-md-12',
          caption: 'Common.Template',
          searchEnable: true,
          sortEnable: true,
          type: 'lookup',
          hidden: true,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        DueDate: {
          displayOrder: 7,
          caption: 'Common.DueDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'datetime',
          hidden: false,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        Timezone: {
          displayOrder: 7,
          caption: 'Common.Timezone',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'timezone',
          hidden: true,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        Day: {
          displayOrder: 6,
          caption: 'Common.Day',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'lookup',
          hidden: true,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        Time: {
          displayOrder: 6,
          caption: 'Common.Time',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'lookup',
          hidden: true,
          inlineEdit: true,
          newForm: true,
          editForm: true,
        },
        Type: {
          displayOrder: 6,
          caption: 'Common.TypeCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-12 col-md-12',
          hidden: false,
          inlineEdit: true,
          newForm: false,
          editForm: false,
        },
        createdDate: {
          displayOrder: 8,
          caption: 'Common.CreatedDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'datetime',
          cssClasses: 'col-12 col-md-12',
          hidden: false,
          inlineEdit: true,
          newForm: false,
          editForm: false,
        },
        createdBy: {
          displayOrder: 9,
          caption: 'Common.CreatedBy',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-12 col-md-12',
          hidden: false,
          inlineEdit: true,
          newForm: false,
          editForm: false,
        },
        TemplateName: {
          displayOrder: 10,
          caption: 'Common.TemplateNameCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '170px',
          type: 'string',
          cssClasses: 'col-12 col-md-12',
          hidden: false,
          inlineEdit: true,
          newForm: false,
          editForm: false,
        },
        templateAction: {
          displayOrder: 11,
          caption: 'Drawer.Action',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-12 col-md-12',
          hidden: false,
          inlineEdit: true,
          newForm: false,
          editForm: false,
        },
      },
      template: {
        name: 'eventTask-grid',
        context: {
          basePath: '/event',
        },
        actions: {
          edit: {
            hidden: true,
          },
          exportCsv: {
            hidden: true,
          },
        },
      },
      dataSource: {
        singularEntity: 'Common.Task',
        pluralEntity: 'Common.Tasks',
        query: memberTasks,
        defaultSort: 'createdDate DESC',
        type: 'graphql',
        model: 'CRMActivity',
        filter(ctx) {
          return {
            where: { CustomerId: this.$route.params.id },
          }
        },
      },
      title: 'memberTasks',
      type: 'list',
    },
    memberContacts: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: true,
        hideSearch: true,
      },
      fields: {
        FirstName: {
          caption: 'Common.FirstNameCaption',
          columnWidth: '180px',
          type: 'string',
          searchEnable: false,
          sortEnable: false,
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.FirstNameRequired')
            },
          ],
        },
        LastName: {
          caption: 'Common.LastNameCaption',
          columnWidth: '180px',
          type: 'string',
          searchEnable: false,
          sortEnable: false,
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.LastNameRequired')
            },
          ],
        },
        Job: {
          caption: 'Common.JobTitle',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '170px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
        Department: {
          displayOrder: 4,
          caption: 'Common.Department',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: false,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
        CellPhone: {
          caption: 'Common.Phone',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '150px',
          type: 'string',
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.PhoneRequired')
            },
            function (value, data) {
              return /^[0-9]\d*$|^$/.test(value) || 'Number must be valid'
            },
          ],
        },
        Email: {
          displayOrder: 3,
          caption: 'Common.EmailCaption',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: false,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.EmailRequired')
            },
            function (value, data) {
              return /.+@.+\..+/.test(value) || 'E-mail must be valid'
            },
          ],
        },
        FullName: {
          displayOrder: 2,
          caption: 'Common.FullName',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: false,
          newForm: false,
          editForm: false,
        },
        createdDate: {
          caption: 'Common.CreatedDate',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'date',
          hidden: true,
          newForm: false,
          editForm: false,
        },
        createdBy: {
          caption: 'Common.CreatedBy',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
        '_CurrentAddress.City': {
          displayOrder: 5,
          caption: 'Common.CurrentAddressCity',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: false,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
        '_CurrentAddress.State': {
          caption: 'Common.CurrentAddressState',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
        '_CurrentAddress.PostalCode': {
          caption: 'Common.CurrentAddressPostalCode',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
        '_CurrentAddress.Country': {
          displayOrder: 6,
          caption: 'Common.Country',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: false,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
      },
      template: {
        name: 'memberContacts-grid',
        context: {
          basePath: '/members',
        },
      },
      dataSource: {
        singularEntity: 'Common.Contact',
        pluralEntity: 'Common.Contacts',
        type: 'rest',
        getData: (ctx) =>
          getCustomData(`Customers/${ctx.$route.params.id}/CutomerContact`),
        defaultSort: 'createdDate DESC',
      },
      itemTitle: 'Common.Contact',
      title: 'Common.Contacts',
      defaultSort: 'createdDate DESC',
    },
    memberEmails: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: false,
        hideFilter: false,
        hideSearch: true,
      },
      hidden: true,
      fields: {
        Title: {
          displayOrder: 2,
          caption: 'Common.TitleCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'strig',
        },
        Status: {
          displayOrder: 3,
          caption: 'Common.Status',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '125px',
          type: 'string',
        },
        createdBy: {
          displayOrder: 4,
          caption: 'Common.CreatedBy',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        createdDate: {
          displayOrder: 5,
          caption: 'Common.CreatedDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '160px',
          type: 'date',
        },
        DueDate: {
          displayOrder: 6,
          caption: 'Common.DueDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '135px',
          type: 'datetime',
        },
        TemplateName: {
          displayOrder: 7,
          caption: 'Common.TemplateNameCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '170px',
          type: 'string',
        },
      },
      template: {
        name: 'memberEmails-grid',
        context: {
          basePath: '/contact',
        },
        actions: {
          new: {
            hidden: true,
          },
          edit: {
            hidden: true,
          },
          delete: {
            hidden: true,
          },
          exportCsv: {
            hidden: true,
          },
        },
      },
      dataSource: {
        singularEntity: 'Common.Task',
        pluralEntity: 'Common.Tasks',
        type: 'rest',
        getData: (ctx) =>
          getCustomData(
            `Customers/${ctx.$route.params.id}/customerCrmActivity`
          ),
        defaultSort: 'createdDate DESC',
      },
      title: 'contactEmails',
      type: 'list',
    },
    associatedMember: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: false,
        hideSearch: false,
      },
      itemTitle: 'Common.AssociateMember',
      fields: {
        CustomerId: {
          displayOrder: 2,
          caption: 'Common.CustomerId',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-12 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: false,
          editForm: false,
        },
        CustomerName: {
          form: {
            caption: 'Common.CustomerName',
            displayOrder: 1,
          },
          displayOrder: 3,
          caption: 'Common.CustomerName',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-12 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: false,
          editForm: false,
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.CustomerNameRequired')
            },
          ],
        },
        NumberOfEmployees: {
          form: {
            caption: 'Common.NumberOfEmployees',
            displayOrder: 1,
          },
          displayOrder: 4,
          caption: 'Common.NumberOfEmployees',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'lookup',
          cssClasses: 'col-12 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: false,
          editForm: false,
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.CustomerNameRequired')
            },
          ],
          dataSource: {
            query: registrationStatusOptions,
            itemText: 'value',
            itemValue: 'key',
            filter(data) {
              return {
                type: 'CompanySize',
              }
            },
          },
        },
        BusinessNumber: {
          displayOrder: 5,
          caption: 'Common.BusinessNumber',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          cssClasses: 'col-12 col-md-6',
          hidden: false,
          inlineEdit: false,
          newForm: false,
          editForm: false,
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.BusinessNameRequired')
            },
          ],
        },
        Type: {
          form: {
            caption: 'Common.Type',
            displayOrder: 3,
          },
          displayOrder: 6,
          caption: 'Common.Type',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'lookup',
          cssClasses: 'col-12 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: false,
          editForm: false,
          dataSource: {
            query: registrationStatusOptions,
            itemText: 'value',
            itemValue: 'key',
            filter(data) {
              return {
                type: 'CustomerType',
              }
            },
          },
        },
        Industry: {
          form: {
            caption: 'Common.Industry',
            displayOrder: 3,
          },
          displayOrder: 6,
          caption: 'Common.Industry',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'lookup',
          cssClasses: 'col-12 col-md-6',
          hidden: false,
          inlineEdit: true,
          newForm: false,
          editForm: false,
          dataSource: {
            query: registrationStatusOptions,
            itemText: 'value',
            itemValue: 'key',
            filter(data) {
              return {
                type: 'Industry',
              }
            },
          },
        },
        Website: {
          form: {
            caption: 'Common.Website',
            displayOrder: 3,
          },
          displayOrder: 7,
          caption: 'Common.Website',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
          newForm: false,
          editForm: false,
        },
        createdDate: {
          caption: 'Common.CreatedDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'date',
          hidden: true,
          newForm: false,
          editForm: false,
        },
        createdBy: {
          caption: 'Common.CreatedBy',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
        },
        '_BillingAddress.AddressLine': {
          form: {
            caption: 'Common.Address',
            displayOrder: 7,
          },
          caption: 'Common.Address',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-12',
        },
        '_BillingAddress.City': {
          form: {
            caption: 'Common.City',
            displayOrder: 8,
          },
          caption: 'Common.City',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-6',
        },
        '_BillingAddress.State': {
          form: {
            caption: 'Common.State',
            displayOrder: 9,
          },
          caption: 'Common.State',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-6',
        },
        '_BillingAddress.PostalCode': {
          form: {
            caption: 'Common.Zip',
            displayOrder: 10,
          },
          caption: 'Common.Zip',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-6',
        },
        '_BillingAddress.Country': {
          form: {
            caption: 'Common.Country',
            displayOrder: 11,
          },
          caption: 'Common.Country',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-6',
        },
        '_ShippingAddress.AddressLine': {
          form: {
            caption: 'Common.Address',
            displayOrder: 12,
          },
          caption: 'Common.Address',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-12',
        },
        '_ShippingAddress.City': {
          form: {
            caption: 'Common.City',
            displayOrder: 12,
          },
          caption: 'Common.City',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-6',
        },
        '_ShippingAddress.State': {
          form: {
            caption: 'Common.State',
            displayOrder: 13,
          },
          caption: 'Common.State',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-6',
        },
        '_ShippingAddress.PostalCode': {
          form: {
            caption: 'Common.Zip',
            displayOrder: 14,
          },
          caption: 'Common.Zip',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-6',
        },
        '_ShippingAddress.Country': {
          form: {
            caption: 'Common.Country',
            displayOrder: 15,
          },
          caption: 'Common.Country',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-6',
        },
        Description: {
          form: {
            caption: 'Common.Description',
            displayOrder: 16,
          },
          caption: 'Common.Description',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-12 col-md-12',
        },
      },
      template: {
        name: 'associatedMember-grid',
        context: {
          basePath: '/member',
        },
      },
      dataSource: {
        singularEntity: 'Common.Members',
        pluralEntity: 'Drawer.Members',
        query: memberList,
        type: 'graphql',
        model: 'Customer',
        filter(ctx) {
          return {
            where: { ParentCustomerId: this.$route.params.id },
          }
        },
        defaultSort: 'createdDate DESC',
      },
      title: 'Drawer.Members',
      defaultSort: 'createdDate DESC',
    },
    allContacts: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: true,
        hideSearch: true,
      },
      fields: {
        FirstName: {
          caption: 'Common.FirstNameCaption',
          columnWidth: '180px',
          type: 'string',
          searchEnable: false,
          sortEnable: false,
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.FirstNameRequired')
            },
          ],
        },
        LastName: {
          caption: 'Common.LastNameCaption',
          columnWidth: '180px',
          type: 'string',
          searchEnable: false,
          sortEnable: false,
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.LastNameRequired')
            },
          ],
        },
        Job: {
          caption: 'Common.JobTitle',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '170px',
          type: 'string',
          hidden: true,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
        Department: {
          displayOrder: 4,
          caption: 'Common.Department',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: false,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
        CellPhone: {
          caption: 'Common.Phone',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '150px',
          type: 'string',
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.PhoneRequired')
            },
            function (value, data) {
              return /^[0-9]\d*$|^$/.test(value) || 'Number must be valid'
            },
          ],
        },
        Email: {
          displayOrder: 3,
          caption: 'Common.EmailCaption',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: false,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.EmailRequired')
            },
            function (value, data) {
              return /.+@.+\..+/.test(value) || 'E-mail must be valid'
            },
          ],
        },
        '_CurrentAddress.City': {
          displayOrder: 5,
          caption: 'Common.CurrentAddressCity',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: false,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
        '_CurrentAddress.Country': {
          displayOrder: 6,
          caption: 'Common.Country',
          searchEnable: false,
          sortEnable: false,
          columnWidth: '180px',
          type: 'string',
          hidden: false,
          newForm: false,
          editForm: false,
          cssClasses: 'col-6 col-md-6',
        },
      },
      template: {
        name: 'memberContacts-grid',
        context: {
          basePath: '/members',
        },
      },
      dataSource: {
        singularEntity: 'Common.Contact',
        pluralEntity: 'Common.Contacts',
        query: contactList,
        type: 'graphql',
        model: 'Contact',
        filter(ctx) {
          return {
            where: {},
          }
        },
        defaultSort: 'createdDate DESC',
      },
      itemTitle: 'Common.Contact',
      title: 'Common.Contacts',
      defaultSort: 'createdDate DESC',
    },
  },
}
