import registrationStatusOptions from './gql/registrationStatusOptions.gql'
import registrationList from './gql/registrationList.gql'
import discountCodes from './gql/discountCodes.gql'
import eventList from './gql/eventlist.gql'
import contactList from './gql/contactList.gql'
import memberList from './gql/memberList.gql'
import { getData } from './rest'
// import { getBPMNData } from './rest/bpmn.js'

export default (ctx) => ({
  Event: {
    Actions: {
      'Embeded Actions': '',
      'General Actions': [],
      'Selected Item Action': ['Delete EventManagement'],
    },
    Child: {},
    DataSource: {
      'Key Field': '',
      'Parent key field': '',
      Type: 'List',
      URL: 'Event',
    },
    general: {
      caption: 'Events',
      name: 'Event',
    },
    Permissions: {
      Groups: '',
    },
    UI: {
      TemplateActions: {},
      'Card View Template': 'VisitingCard0',
      Width: '50%',
      Height: '',
      TemplateHelpers: {},
      IsEditable: 'No',
      'Display Order': '',
      'Map View Template': '',
      'Calendar View Template': 'calendarEvent',
      'List View Template': '',
      'Detail View': 'tab',
      Column: '',
      'Tile View': '',
      Templates: {
        calendarEvent:
          '<style>\n    .cal-content{\n        color: white;\n        display: flex;\n        flex-direction: row;\n        justify-content: space-between;\n    }\n     .cal-content i{\n          color: white;\n     }\n    .cal-content.Event{\n        background: green;\n    }\n    .cal-content{\n        padding: 0 2px;\n     }\n    .fc-day-grid-event{\n        padding: 0;\n        border: 0;\n    }\n</style>\n<div class="cal-content {{node.__typename}}">\n    <span class="fc-title">\n        {{title}}\n    </span>\n   <span class="cal-del-act" onClick="invokeAction(\'deleteEvent\',\'{{node.id}}\',\'{{node.__typename}}\')">\n        <i class="fa fa-trash" title="delete event"></i>\n    </span>\n</div>\n',
        EndDate: '<div>{{#if EndDate}}{{getdateTime EndDate}}{{/if}}</div>',
        StartDate:
          '<div>{{#if StartDate}}{{getdateTime StartDate}}{{/if}}</div>',
        VisitingCard0: 'EventMangment_Card_View',
        Title:
          '<div onclick="invokeAction(\'goToDetails\', this)" businessType="{{BusinessType}}" data-action="edit" data-bind="ID={{id}}" style="cursor: pointer;color: #1a73e8;"> {{Title}} </div>',
      },
      decorator: {
        Attachment: '',
        LinkedinURL: '',
      },
    },
    views: {
      'All Events': {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: false,
          hideSearch: true,
        },
        default: false,
        fields: {
          Title: {
            displayOrder: 2,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          StartDate: {
            displayOrder: 3,
            caption: 'Start Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
          },
          EndDate: {
            displayOrder: 3,
            caption: 'End Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
          },
          Privacy: {
            displayOrder: 4,
            caption: 'Privacy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          Tags: {
            displayOrder: 5,
            caption: 'Tags',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          VenueName: {
            displayOrder: 6,
            caption: 'Venue',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          '_VenueAddress.AddressLine': {
            displayOrder: 7,
            caption: 'Address',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          '_VenueAddress.City': {
            displayOrder: 8,
            caption: 'City',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          '_VenueAddress.State': {
            displayOrder: 9,
            caption: 'State',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          '_VenueAddress.PostalCode': {
            displayOrder: 10,
            caption: 'Postal Code',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          '_VenueAddress.Country': {
            displayOrder: 11,
            caption: 'Country',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          Currency: {
            displayOrder: 12,
            caption: 'Currency',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          createdDate: {
            displayOrder: 13,
            caption: 'Created Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
          },
        },
        template: {
          name: 'link-grid',
          context: {
            basePath: '/event',
          },
        },
        dataSource: {
          query: eventList,
          defaultSort: 'createdDate DESC',
          type: 'graphql',
          model: 'Event',
        },
        title: 'All Events',
        type: 'list',
      },
      Past: {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: false,
          hideSearch: true,
        },
        default: false,
        fields: {
          Title: {
            displayOrder: 2,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          StartDate: {
            displayOrder: 3,
            caption: 'Start Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
          },
          EndDate: {
            displayOrder: 3,
            caption: 'End Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
          },
          Privacy: {
            displayOrder: 4,
            caption: 'Privacy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          Tags: {
            displayOrder: 5,
            caption: 'Tags',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          VenueName: {
            displayOrder: 6,
            caption: 'Venue',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          '_VenueAddress.AddressLine': {
            displayOrder: 7,
            caption: 'Address',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          '_VenueAddress.City': {
            displayOrder: 8,
            caption: 'City',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          '_VenueAddress.State': {
            displayOrder: 9,
            caption: 'State',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          '_VenueAddress.PostalCode': {
            displayOrder: 10,
            caption: 'Postal Code',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          '_VenueAddress.Country': {
            displayOrder: 11,
            caption: 'Country',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          Currency: {
            displayOrder: 12,
            caption: 'Currency',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          createdDate: {
            displayOrder: 13,
            caption: 'Created Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
          },
        },
        template: {
          name: 'link-grid',
          context: {
            basePath: '/event',
          },
        },
        dataSource: {
          query: eventList,
          defaultSort: 'createdDate DESC',
          type: 'graphql',
          model: 'Event',
          filter: {
            where: {
              and: [{ EndDate: { lte: new Date() } }],
            },
          },
        },
        title: 'Past',
        type: 'list',
      },
    },
  },

  Registrations: {
    child: {},
    dataSource: {
      FormID: 'EventsAdvSearch',
      'Key Field': '',
      'Parent key field': '',
      Type: 'List',
      URL: 'Registration',
    },
    general: {
      caption: 'Registrations',
      name: 'Registration',
    },
    permissions: {
      Groups: '',
    },
    ui: {
      MobileViewTemplate: {
        isActive: true,
        templateName: 'Event_Registation_Mobile',
      },
      TemplateActions: {},
      Checkbox: 'True',
      'Card View Template': 'VisitingCard0',
      Width: '50%',
      Height: '',
      TemplateHelpers: {},
      'Display Order': '',
      'Map View Template': '',
      'List View Template': '',
      'Detail View': 'tab',
      Column: '',
      'Tile View': 'now',
      'App Type': 'View',
      Templates: {
        VisitingCard0: 'Registrations_Card_View',
        Status:
          '<div title="{{Status}}"><style>.reg-status {\n                  font-size: 10px;\n                            display: inline-block;\n                            color: #fff;\n                            margin-right: 5px;\n                            margin-bottom: 0px;\n                            padding: 3px 10px !important;\n                            border-radius: 20px !important;\n                            text-transform: capitalize;\n                        }\n                      .reg-success {\n                                      background-color: #0cb14b;\n                    }\n                      .reg-fail {\n                                      background-color: #f25955;\n                    }\n                      .reg-refund {\n                                      background-color: #3fa5ff;\n                    }\n                    .reg-parefund {\n                                      background-color: #b9b9b9;\n                    }\n                      .reg-parrefund {\n                                      background-color: #f4b400;\n                    }</style><div class="reg-status {{getStatusColor Status}}"> {{getCapitalResult Status}} </div></div>',
        SyncStatus:
          '<div><i class="{{ShowSyncField SFRegistrationId}}" style="{{getColor SFRegistrationId}}" onclick="invokeAction(\'changeSyncStatus\',this)" node={{node.id}}> </i></div>',
        CheckIn:
          '<style>\n    .checkin-btn {\ncolor: #fff;\npadding: 3px 10px !important;\n    background-color: #3fa5ff !important;;\nfont-size: 12px;\nborder-radius: 2px;\ncursor: pointer;\n}\n.check-label {\n        color: #1a73e8;\nfont-size: 13px;\n}\n</style>\n{{#ifStatus Status}}\n<div title="CheckIn">\n    {{#if CheckIn}}<span class="check-label">\n        <i class="fa fa-check" style="color: #1a73e8;margin-top:3px;" node={{node.id}}> </i>Checked in </span>\n    <span class="check-label">{{date_diff CheckIn}}</span>\n    {{else}}\n    <span onclick="invokeAction(\'CheckIn\',this)" class="checkin-btn">Check in</span>\n    {{/if}}\n</div>\n{{else}} <div style="height: 100%;" title=""></div>{{/ifStatus}}',
        FullName:
          '<div onclick="invokeAction(\'goToDetails\', this)" data-action="edit" data-bind="ID={{id}}" style="cursor: pointer;color: #1a73e8;"> {{FullName}} </div>',
      },
      decorator: {
        Attachment: '',
        LinkedinURL: '',
      },
    },
    views: {
      Registrations: {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: true,
          hideSearch: false,
        },
        default: true,
        fields: {
          EventName: {
            displayOrder: 6,
            caption: 'EventName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            cssClasses: 'col-12 col-md-12',
          },
          PaymentMethod: {
            displayOrder: 10,
            caption: 'PaymentMethod',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          CompanyName: {
            displayOrder: 4,
            caption: 'Organization',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'richtext',
          },
          Phone: {
            displayOrder: 5,
            caption: 'Phone',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
            type: 'string',
          },
          Status: {
            displayOrder: 9,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
            type: 'lookup',
            dataSource: {
              query: registrationStatusOptions,
              itemText: 'value',
              itemValue: 'key',
              filter(data) {
                debugger
                return {
                  type: data.EventName,
                }
              },
            },
            // template: {
            //   name: 'issue-grid',
            //   params: {
            //     // eslint-disable-next-line no-template-curly-in-string
            //     route: '/event',
            //   },
            // },
            // items: [
            //   {
            //     text: 'Success Payment',
            //     value: 'Success',
            //   },
            //   {
            //     text: 'Pending Payment',
            //     value: 'Pending',
            //   },
            // ],
          },
          RegistrationId: {
            displayOrder: 6,
            caption: 'RegistrationId',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            inlineEdit: false,
            newForm: false,
            editForm: false,
          },
          createdDate: {
            displayOrder: 11,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
            inlineEdit: false,
            newForm: true,
            editForm: false,
          },
          TicketQuantity: {
            displayOrder: 9,
            caption: 'Attendees',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'number',
          },
          FullName: {
            displayOrder: 2,
            caption: 'Full Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
            inlineEdit: false,
            newForm: false,
            editForm: false,
          },
          TotalAmount: {
            displayOrder: 8,
            caption: 'TotalAmount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'number',
          },
          Email: {
            displayOrder: 3,
            caption: 'Email',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
            readonly(value, data) {
              const firstName = data.FirstName
              return firstName && firstName.length <= 5
            },
            rules: [
              (v) => {
                return !!v || 'E-mail is required'
              },
              function (value, data) {
                return /.+@.+\..+/.test(value) || 'E-mail must be valid'
              },
            ],
          },
          action: {
            displayOrder: 11,
            caption: 'Action',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '130px',
            type: 'action',
            inlineEdit: false,
            newForm: false,
            editForm: false,
            condtion: ({ item, items, index }) => {
              return true
            },
          },
          FirstName: {
            displayOrder: 2,
            caption: 'First Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
            hidden: true,
            inlineEdit: true,
            newForm: true,
            editForm: false,
            rules: [
              (v) => {
                return !!v || 'FirstName is required'
              },
              (v) => {
                return (
                  (v && v.length <= 10) ||
                  'Name must be less than 10 characters'
                )
              },
            ],
          },
          // Images: {
          //   displayOrder: 1,
          //   caption: 'Images',
          //   hidden: true,
          //   columnWidth: '150px',
          //   type: 'file',
          // },
        },
        template: {
          name: 'registration-grid',
          context: {
            basePath: '/registration',
          },
        },
        dataSource: {
          query: registrationList,
          defaultSort: 'createdDate DESC',
          type: 'graphql',
          model: 'Registration',
          filter: {
            where: {},
          },
          // end of gql
          // type: 'rest',
          // getData: getData('Registration'),
        },
        title: 'Registrations',
        type: 'list',
        // type: 'card',
        // type: 'calendar',
        // type: 'path',
        // path: '/event-dashboard/abc'
      },
      'Abandoned Registrations': {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: false,
          hideSearch: true,
        },
        fields: {
          EventName: {
            displayOrder: 6,
            caption: 'EventName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            cssClasses: 'col-12 col-md-12',
          },
          PaymentMethod: {
            displayOrder: 10,
            caption: 'PaymentMethod',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          CompanyName: {
            displayOrder: 4,
            caption: 'Organization',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'richtext',
          },
          Phone: {
            displayOrder: 5,
            caption: 'Phone',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
            type: 'string',
          },
          Status: {
            displayOrder: 9,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
            type: 'lookup',
            dataSource: {
              query: registrationStatusOptions,
              itemText: 'value',
              itemValue: 'key',
              filter(data) {
                debugger
                return {
                  type: data.EventName,
                }
              },
            },
            // template: {
            //   name: 'issue-grid',
            //   params: {
            //     // eslint-disable-next-line no-template-curly-in-string
            //     route: '/event',
            //   },
            // },
            // items: [
            //   {
            //     text: 'Success Payment',
            //     value: 'Success',
            //   },
            //   {
            //     text: 'Pending Payment',
            //     value: 'Pending',
            //   },
            // ],
          },
          RegistrationId: {
            displayOrder: 6,
            caption: 'RegistrationId',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            inlineEdit: false,
            newForm: false,
            editForm: false,
          },
          createdDate: {
            displayOrder: 11,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
            inlineEdit: false,
            newForm: true,
            editForm: false,
          },
          TicketQuantity: {
            displayOrder: 9,
            caption: 'Attendees',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'number',
          },
          FullName: {
            displayOrder: 2,
            caption: 'Full Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
            inlineEdit: false,
            newForm: false,
            editForm: false,
          },
          TotalAmount: {
            displayOrder: 8,
            caption: 'TotalAmount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'number',
          },
          Email: {
            displayOrder: 3,
            caption: 'Email',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
            readonly(value, data) {
              const firstName = data.FirstName
              return firstName && firstName.length <= 5
            },
            rules: [
              (v) => {
                return !!v || 'E-mail is required'
              },
              function (value, data) {
                return /.+@.+\..+/.test(value) || 'E-mail must be valid'
              },
            ],
          },
          action: {
            displayOrder: 11,
            caption: 'Action',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '130px',
            type: 'action',
            inlineEdit: false,
            newForm: false,
            editForm: false,
            condtion: ({ item, items, index }) => {
              return true
            },
          },
          FirstName: {
            displayOrder: 2,
            caption: 'First Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
            hidden: true,
            inlineEdit: true,
            newForm: true,
            editForm: false,
            rules: [
              (v) => {
                return !!v || 'FirstName is required'
              },
              (v) => {
                return (
                  (v && v.length <= 10) ||
                  'Name must be less than 10 characters'
                )
              },
            ],
          },
          // Images: {
          //   displayOrder: 1,
          //   caption: 'Images',
          //   hidden: true,
          //   columnWidth: '150px',
          //   type: 'file',
          // },
        },
        template: {
          name: 'registration-grid',
          context: {
            basePath: '/registration',
          },
        },
        dataSource: {
          query: registrationList,
          defaultSort: 'createdDate DESC',
          type: 'graphql',
          model: 'Registration',
          filter: {
            where: { Status: 'Failed' },
          },
          // end of gql
          // type: 'rest',
          // getData: getData('Registration'),
        },
        title: 'Abandoned Registrations',
        type: 'list',
        // type: 'card',
        // type: 'calendar',
        // type: 'path',
        // path: '/event-dashboard/abc'
      },
      eventRegistrations: {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: false,
          hideSearch: true,
        },
        hidden: true,
        fields: {
          EventName: {
            displayOrder: 6,
            caption: 'EventName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            cssClasses: 'col-12 col-md-12',
          },
          PaymentMethod: {
            displayOrder: 10,
            caption: 'PaymentMethod',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          CompanyName: {
            displayOrder: 4,
            caption: 'Organization',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'richtext',
          },
          Phone: {
            displayOrder: 5,
            caption: 'Phone',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
            type: 'string',
          },
          Status: {
            displayOrder: 9,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
            type: 'lookup',
            dataSource: {
              query: registrationStatusOptions,
              itemText: 'value',
              itemValue: 'key',
              filter(data) {
                debugger
                return {
                  type: data.EventName,
                }
              },
            },
            // template: {
            //   name: 'issue-grid',
            //   params: {
            //     // eslint-disable-next-line no-template-curly-in-string
            //     route: '/event',
            //   },
            // },
            // items: [
            //   {
            //     text: 'Success Payment',
            //     value: 'Success',
            //   },
            //   {
            //     text: 'Pending Payment',
            //     value: 'Pending',
            //   },
            // ],
          },
          RegistrationId: {
            displayOrder: 6,
            caption: 'RegistrationId',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            inlineEdit: false,
            newForm: false,
            editForm: false,
          },
          createdDate: {
            displayOrder: 11,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
            inlineEdit: false,
            newForm: true,
            editForm: false,
          },
          TicketQuantity: {
            displayOrder: 9,
            caption: 'Attendees',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'number',
          },
          FullName: {
            displayOrder: 2,
            caption: 'Full Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
            inlineEdit: false,
            newForm: false,
            editForm: false,
          },
          TotalAmount: {
            displayOrder: 8,
            caption: 'TotalAmount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'number',
          },
          Email: {
            displayOrder: 3,
            caption: 'Email',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
            readonly(value, data) {
              const firstName = data.FirstName
              return firstName && firstName.length <= 5
            },
            rules: [
              (v) => {
                return !!v || 'E-mail is required'
              },
              function (value, data) {
                return /.+@.+\..+/.test(value) || 'E-mail must be valid'
              },
            ],
          },
          action: {
            displayOrder: 11,
            caption: 'Action',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '130px',
            type: 'action',
            inlineEdit: false,
            newForm: false,
            editForm: false,
            condtion: ({ item, items, index }) => {
              return true
            },
          },
          FirstName: {
            displayOrder: 2,
            caption: 'First Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
            hidden: true,
            inlineEdit: true,
            newForm: true,
            editForm: false,
            rules: [
              (v) => {
                return !!v || 'FirstName is required'
              },
              (v) => {
                return (
                  (v && v.length <= 10) ||
                  'Name must be less than 10 characters'
                )
              },
            ],
          },
          // Images: {
          //   displayOrder: 1,
          //   caption: 'Images',
          //   hidden: true,
          //   columnWidth: '150px',
          //   type: 'file',
          // },
        },
        template: {
          name: 'registration-grid',
          context: {
            basePath: '/registration',
          },
        },
        dataSource: {
          query: registrationList,
          defaultSort: 'createdDate DESC',
          type: 'graphql',
          model: 'Registration',
          filter: {
            where: {
              EventId: ctx.$route.params.id,
            },
          },
          // end of gql
          // type: 'rest',
          // getData: getData('Registration'),
        },
        title: 'Registrations',
        type: 'list',
        // type: 'card',
        // type: 'calendar',
        // type: 'path',
        // path: '/event-dashboard/abc'
      },
      registrationSessions: {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: false,
          hideSearch: true,
        },
        hidden: true,
        fields: {
          Name: {
            displayOrder: 1,
            caption: 'Name',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '150px',
            type: 'string',
          },
          StartTime: {
            displayOrder: 2,
            caption: 'Start Time',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '130px',
            type: 'string',
          },
          EndTime: {
            displayOrder: 3,
            caption: 'End Time',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '130px',
            type: 'string',
          },
          StartDate: {
            displayOrder: 4,
            caption: 'Start Date',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '130px',
            type: 'Date',
          },
          EndDate: {
            displayOrder: 5,
            caption: 'End Date',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '130px',
            type: 'date',
          },
          Type: {
            displayOrder: 6,
            caption: 'Type',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '100px',
            type: 'string',
          },
          Location: {
            displayOrder: 7,
            caption: 'Location',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '180px',
            type: 'string',
          },
        },
        template: {
          name: 'registration-grid',
          context: {
            basePath: '/registration',
          },
        },
        dataSource: {
          // query: registrationList,
          // defaultSort: 'createdDate DESC',
          // type: 'graphql',
          // model: 'Registration',
          // filter: {
          //   where: {
          //     EventId: ctx.$route.params.id,
          //   },
          // },
          // end of gql
          type: 'rest',
          getData: getData(
            `/Registrations/${ctx.$route.params.id}/SessionListId`
          ),
        },
        title: 'Sessions',
        type: 'list',
        // type: 'card',
        // type: 'calendar',
        // type: 'path',
        // path: '/event-dashboard/abc'
      },
      registrationAttendees: {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: false,
          hideSearch: true,
        },
        hidden: true,
        fields: {
          FullName: {
            displayOrder: 2,
            caption: 'Full Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          Email: {
            displayOrder: 3,
            caption: 'Email',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          CompanyName: {
            displayOrder: 4,
            caption: 'Organization',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          TicketName: {
            displayOrder: 5,
            caption: 'Ticket',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          TicketAmount: {
            displayOrder: 6,
            caption: 'Ticket Amount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          SeatNumber: {
            displayOrder: 7,
            caption: 'Seat Number',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          CheckIn: {
            displayOrder: 8,
            caption: 'CheckIn',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
          createdDate: {
            displayOrder: 9,
            caption: 'Created Date ',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
          },
        },
        template: {
          name: 'registration-grid',
          context: {
            basePath: '/registration',
          },
        },
        dataSource: {
          // query: registrationAttendee,
          // defaultSort: 'createdDate DESC',
          // type: 'graphql',
          // model: 'Attendee',
          // filter: {
          //   where: { RegistrationId: ctx.$route.params.id },
          // },
          type: 'rest',
          getData: getData(`/Registrations/${ctx.$route.params.id}/attendee`),
        },
        title: 'Registrations',
        type: 'list',
      },
      registrationEmails: {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: false,
          hideSearch: true,
        },
        hidden: true,
        fields: {
          Title: {
            displayOrder: 1,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          Status: {
            displayOrder: 2,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          Action: {
            displayOrder: 3,
            caption: 'Wait For',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          Category: {
            displayOrder: 4,
            caption: 'Category',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          TemplateName: {
            displayOrder: 8,
            caption: 'TemplateName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          createdBy: {
            displayOrder: 7,
            caption: 'createdBy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          createdDate: {
            displayOrder: 6,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          DueDate: {
            displayOrder: 5,
            caption: 'DueDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
        },
        template: {
          name: 'registration-grid',
          context: {
            basePath: '/registration',
          },
        },
        dataSource: {
          type: 'rest',
          getData: getData(
            `/Registrations/${ctx.$route.params.id}/SessionListId`
          ),
        },
        title: 'Emails',
        type: 'list',
      },
      Registration: {
        DefaultSort: 'createdDate DESC',
        DataSource: {
          FormID: 'RegistrationDetailForm',
          Aggregation: '',
          'Default view': '',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Key Field': '',
          'Sharepoint Action': 'Edit',
          Type: 'Form',
          URL: 'OfferCode',
        },
        template: {
          name: 'registration-grid',
          context: {
            basePath: '/registration',
          },
        },
        Fields: {
          LastName: {
            displayOrder: 3,
            caption: 'LastName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          EventName: {
            displayOrder: 6,
            caption: 'EventName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          PaymentMethod: {
            displayOrder: 10,
            caption: 'PaymentMethod',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          Phone: {
            displayOrder: 5,
            caption: 'Phone',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          Status: {
            displayOrder: 9,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          RegistrationId: {
            displayOrder: 1,
            caption: 'RegistrationId',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          createdDate: {
            displayOrder: 11,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          TicketQuantity: {
            displayOrder: 7,
            caption: 'TicketQuantity',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          FirstName: {
            displayOrder: 2,
            caption: 'FirstName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          TotalAmount: {
            displayOrder: 8,
            caption: 'TotalAmount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          Email: {
            displayOrder: 4,
            caption: 'Email',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
        },
        Query: '',
        hidden: true,
        type: 'Form',
        title: 'Registration',
      },
    },
  },

  DiscountCodes: {
    actions: {
      'Embeded Actions': '',
      'General Actions': ['Create Registration'],
      'Selected Item Action': [],
    },
    child: {},
    dataSource: {
      FormID: 'EventsAdvSearch',
      'Key Field': '',
      'Parent key field': '',
      Type: 'List',
      URL: 'Offercode',
    },
    general: {
      caption: 'OfferCodes',
      name: 'OfferCode',
    },
    permissions: {
      Groups: '',
    },
    ui: {
      MobileViewTemplate: {
        isActive: true,
        templateName: 'Event_Registation_Mobile',
      },
      TemplateActions: {},
      Checkbox: 'True',
      'Card View Template': 'VisitingCard0',
      Width: '50%',
      Height: '',
      TemplateHelpers: {},
      'Display Order': '',
      'Map View Template': '',
      'List View Template': '',
      'Detail View': 'tab',
      Column: '',
      'Tile View': 'now',
      'App Type': 'View',
      Templates: {
        VisitingCard0: 'Registrations_Card_View',
        Status:
          '<div title="{{Status}}"><style>.reg-status {\n                  font-size: 10px;\n                            display: inline-block;\n                            color: #fff;\n                            margin-right: 5px;\n                            margin-bottom: 0px;\n                            padding: 3px 10px !important;\n                            border-radius: 20px !important;\n                            text-transform: capitalize;\n                        }\n                      .reg-success {\n                                      background-color: #0cb14b;\n                    }\n                      .reg-fail {\n                                      background-color: #f25955;\n                    }\n                      .reg-refund {\n                                      background-color: #3fa5ff;\n                    }\n                    .reg-parefund {\n                                      background-color: #b9b9b9;\n                    }\n                      .reg-parrefund {\n                                      background-color: #f4b400;\n                    }</style><div class="reg-status {{getStatusColor Status}}"> {{getCapitalResult Status}} </div></div>',
        SyncStatus:
          '<div><i class="{{ShowSyncField SFRegistrationId}}" style="{{getColor SFRegistrationId}}" onclick="invokeAction(\'changeSyncStatus\',this)" node={{node.id}}> </i></div>',
        CheckIn:
          '<style>\n    .checkin-btn {\ncolor: #fff;\npadding: 3px 10px !important;\n    background-color: #3fa5ff !important;;\nfont-size: 12px;\nborder-radius: 2px;\ncursor: pointer;\n}\n.check-label {\n        color: #1a73e8;\nfont-size: 13px;\n}\n</style>\n{{#ifStatus Status}}\n<div title="CheckIn">\n    {{#if CheckIn}}<span class="check-label">\n        <i class="fa fa-check" style="color: #1a73e8;margin-top:3px;" node={{node.id}}> </i>Checked in </span>\n    <span class="check-label">{{date_diff CheckIn}}</span>\n    {{else}}\n    <span onclick="invokeAction(\'CheckIn\',this)" class="checkin-btn">Check in</span>\n    {{/if}}\n</div>\n{{else}} <div style="height: 100%;" title=""></div>{{/ifStatus}}',
        FullName:
          '<div onclick="invokeAction(\'goToDetails\', this)" data-action="edit" data-bind="ID={{id}}" style="cursor: pointer;color: #1a73e8;"> {{FullName}} </div>',
      },
      decorator: {
        Attachment: '',
        LinkedinURL: '',
      },
    },
    views: {
      'Discount Codes': {
        default: true,
        defaultSort: 'createdDate DESC',
        fields: {
          currentUsageCount: {
            displayOrder: 9,
            caption: 'Current Usage Count',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '220px',
            type: 'number',
          },
          codeTitle: {
            displayOrder: 1,
            caption: 'Code',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
          isActive: {
            displayOrder: 4,
            caption: 'Active',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '120px',
            // type: 'string',
          },
          validTill: {
            displayOrder: 7,
            caption: 'Valid Till',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'date',
          },
          maxUsageCount: {
            displayOrder: 8,
            caption: 'Max Usage Count',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            // type: 'number',
          },
          offerValue: {
            displayOrder: 5,
            caption: 'Offer Value',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            // type: 'string',
          },
          minApplicableOrderAmount: {
            displayOrder: 6,
            caption: 'Min Applicable Amount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '220px',
            // type: 'number',
          },
          createdDate: {
            displayOrder: 10,
            caption: 'Created Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '250px',
            type: 'date',
          },
          isPercent: {
            displayOrder: 3,
            caption: 'Percent',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            // type: 'string',
          },
        },
        template: {
          name: 'link-grid',
          context: {
            basePath: '/discountcodes',
          },
        },
        dataSource: {
          query: discountCodes, // getItems('users'),
          filter: {
            limit: '10',
            order: 'createdDate DESC',
            skip: '0',
            where: {},
          },
          defaultSort: 'createdDate DESC',
          type: 'graphql',
          // newItem: ,
        },
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: true,
          hideSearch: false,
        },
        title: 'Discount Codes',
        model: 'OfferCode',
      },
      'Discount Code': {
        default: true,
        defaultSort: 'createdDate DESC',
        fields: {
          currentUsageCount: {
            displayOrder: 9,
            caption: 'Current Usage Count',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '220px',
            type: 'number',
          },
          codeTitle: {
            displayOrder: 1,
            caption: 'Code',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
          isActive: {
            displayOrder: 4,
            caption: 'Active',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '120px',
            type: 'string',
          },
          validTill: {
            displayOrder: 7,
            caption: 'Valid Till',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'date',
          },
          maxUsageCount: {
            displayOrder: 8,
            caption: 'Max Usage Count',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
          offerValue: {
            displayOrder: 5,
            caption: 'Offer Value',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          minApplicableOrderAmount: {
            displayOrder: 6,
            caption: 'Min Applicable Amount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '220px',
            type: 'string',
          },
          createdDate: {
            displayOrder: 10,
            caption: 'Created Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '250px',
            type: 'date',
          },
          isPercent: {
            displayOrder: 3,
            caption: 'Percent',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
        },
        template: {
          name: 'link-grid',
          context: {
            basePath: '/discountcodes',
          },
        },
        dataSource: {
          query: discountCodes, // getItems('users'),
          filter: {
            limit: '5',
            order: 'createdDate DESC',
            skip: '0',
            where: {},
          },
          defaultSort: 'createdDate DESC',
          type: 'graphql',
          // newItem: ,
        },
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: true,
          hideSearch: false,
        },
        title: 'Discount Code',
        model: 'OfferCode',
      },
    },
  },

  EventCustomers: {
    action: {
      'Embeded Actions': '',
      'General Actions': ['Add EventCustomer'],
      'Selected Item Action': ['Edit EventCustomer', 'Delete EventCustomer'],
    },
    child: {},
    dataSource: {
      Aggregation: '',
      'Default view': '',
      'Key Field': '',
      'Parent key field': '',
      Type: 'List',
      URL: 'Customer',
    },
    general: {
      caption: 'Members',
      name: 'Customer',
    },
    permissions: {
      Groups: [],
      Type: '',
    },
    ui: {
      'Card View Template': 'VisitingCard0',
      Width: '50 %',
      Height: '',
      TemplateHelpers: {},
      'Display Order': '',
      'Map View Template': '',
      'List View Template': '',
      'Detail View': '',
      Column: '',
      'Tile View': '',
      'App Type': 'View',
      Templates: {
        VisitingCard0: 'CommerceCustomers_Card_View',
      },
      decorator: {
        'Field icon': {
          CallPreference: 'fa fa-check|fa fa-times',
          EmailSubscription: 'fa fa-check|fa fa-times',
        },
      },
    },
    views: {
      Members: {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: true,
          hideSearch: false,
        },
        fields: {
          FirstName: {
            displayOrder: 2,
            caption: 'FirstName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          LastName: {
            displayOrder: 3,
            caption: 'LastName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          Email: {
            displayOrder: 4,
            caption: 'Email',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          BusinessNumber: {
            displayOrder: 5,
            caption: 'BusinessNumber',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          createdDate: {
            displayOrder: 6,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'date',
            newForm: false,
            editForm: false,
          },
          Tags: {
            caption: 'Tags',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
            hidden: true,
            newForm: true,
            editForm: true,
          },
          '_BillingAddress.AddressLine': {
            caption: 'Address',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
            hidden: true,
            newForm: true,
            editForm: true,
          },
          '_BillingAddress.City': {
            caption: 'City',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
            hidden: true,
            newForm: true,
            editForm: true,
          },
          '_BillingAddress.State': {
            caption: 'State',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
            hidden: true,
            newForm: true,
            editForm: true,
          },
          '_BillingAddress.PostalCode': {
            caption: 'Zip',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
            hidden: true,
            newForm: true,
            editForm: true,
          },
          '_BillingAddress.Country': {
            caption: 'Country',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
            hidden: true,
            newForm: true,
            editForm: true,
          },
          Description: {
            caption: 'Description',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
            hidden: true,
            newForm: true,
            editForm: true,
            cssClasses: 'col-12 col-md-12',
          },
        },
        template: {
          name: 'link-grid',
          context: {
            basePath: '/EventCustomers',
          },
        },
        dataSource: {
          query: memberList,
          filter: {
            limit: '10',
            order: 'createdDate DESC',
            skip: '0',
            where: {},
          },
          type: 'graphql',
          model: 'Customer',
          defaultSort: 'createdDate DESC',
        },
        title: 'Members',
        defaultSort: 'createdDate DESC',
      },
    },
  },

  Contacts: {
    dataSouce: {
      Type: 'List',
      URL: 'Contact',
    },
    general: {
      caption: 'Contacts',
      name: 'Contact',
    },
    permissions: {
      groups: '',
    },
    ui: {
      checkbox: true,
      'Card View Template': '',
      width: '',
      height: '',
      TemplateHelpers: {},
      'Display Order': '',
      'Map View Template': '',
      'List View Template': '',
      Column: '',
      'Tile View': 'now',
      'App Type': 'View',
      Templates: {
        FullName:
          '<div onclick="invokeAction(\'goToDetails\', this)" data-action="edit" data-bind="ID={{id}}" style="cursor: pointer;color: blue;"> {{FullName}} </div>',
      },
      decorator: {
        Attachment: '',
        'Field icon': {
          isActive: 'fa fa-check|fa fa-times',
          isEarning: 'fa fa-check|fa fa-times',
        },
        LinkedinURL: '',
      },
    },
    views: {
      Contacts: {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: true,
          hideSearch: false,
        },
        fields: {
          FirstName: {
            caption: 'First Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            hidden: true,
            newForm: true,
            editForm: true,
            cssClasses: 'col-12 col-md-12',
          },
          LastName: {
            caption: 'Last Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            hidden: true,
            newForm: true,
            editForm: true,
            cssClasses: 'col-12 col-md-12',
          },
          Type: {
            displayOrder: 8,
            caption: 'Type',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'lookup',
            newForm: true,
            editForm: true,
            cssClasses: 'col-12 col-md-12',
            dataSource: {
              query: registrationStatusOptions,
              itemText: 'value',
              itemValue: 'key',
              filter(data) {
                return {
                  type: 'CRMContactType',
                }
              },
            },
          },
          Job: {
            displayOrder: 4,
            caption: 'Job Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            newForm: true,
            editForm: true,
            cssClasses: 'col-12 col-md-12',
          },
          Department: {
            caption: 'Department',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'lookup',
            hidden: true,
            newForm: true,
            editForm: true,
            cssClasses: 'col-12 col-md-12',
            dataSource: {
              query: registrationStatusOptions,
              itemText: 'value',
              itemValue: 'key',
              filter(data) {
                return {
                  type: 'CRMDepartment',
                }
              },
            },
          },
          CellPhone: {
            displayOrder: 7,
            caption: 'Phone',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            newForm: true,
            editForm: true,
            cssClasses: 'col-12 col-md-12',
          },
          Email: {
            displayOrder: 3,
            caption: 'Email',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            newForm: true,
            editForm: true,
            cssClasses: 'col-12 col-md-12',
          },
          FullName: {
            displayOrder: 2,
            caption: 'Full Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            hidden: false,
            newForm: false,
            editForm: false,
          },
          Organization: {
            displayOrder: 5,
            caption: 'Organization',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            newForm: false,
            editForm: false,
          },
          Country: {
            displayOrder: 6,
            caption: 'Country',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            newForm: false,
            editForm: false,
          },
          createdDate: {
            displayOrder: 9,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'date',
            newForm: false,
            editForm: false,
          },
        },
        template: {
          name: 'link-grid',
          context: {
            basePath: '/contacts',
          },
        },
        dataSource: {
          query: contactList,
          filter: {
            where: {},
          },
          type: 'graphql',
          model: 'Contact',
          defaultSort: 'createdDate DESC',
        },
        default: true,
        title: 'Contacts',
        defaultSort: 'createdDate DESC',
      },
    },
  },
})
