import registrationStatusOptions from './gql/registrationStatusOptions.gql'
import registrationList from './gql/registrationList.gql'
import discountCodes from './gql/discountCodes.gql'
import eventList from './gql/eventlist.gql'
// import { getItems } from './rest'

export default (ctx) => ({
  EventsManagement: {
    Actions: {
      'Embeded Actions': '',
      'General Actions': [],
      'Selected Item Action': [
        'Edit EventManagement',
        'Clone EventManagement',
        'Delete EventManagement',
      ],
    },
    Child: {},
    DataSource: {
      'Key Field': '',
      'Parent key field': '',
      Type: 'List',
      URL: 'Event',
    },
    general: {
      caption: 'Events',
      name: 'Event',
    },
    Permissions: {
      Groups: '',
    },
    UI: {
      TemplateActions: {},
      'Card View Template': 'VisitingCard0',
      Width: '50%',
      Height: '',
      TemplateHelpers: {},
      IsEditable: 'No',
      'Display Order': '',
      'Map View Template': '',
      'Calendar View Template': 'calendarEvent',
      'List View Template': '',
      'Detail View': 'tab',
      Column: '',
      'Tile View': '',
      Templates: {
        calendarEvent:
          '<style>\n    .cal-content{\n        color: white;\n        display: flex;\n        flex-direction: row;\n        justify-content: space-between;\n    }\n     .cal-content i{\n          color: white;\n     }\n    .cal-content.Event{\n        background: green;\n    }\n    .cal-content{\n        padding: 0 2px;\n     }\n    .fc-day-grid-event{\n        padding: 0;\n        border: 0;\n    }\n</style>\n<div class="cal-content {{node.__typename}}">\n    <span class="fc-title">\n        {{title}}\n    </span>\n   <span class="cal-del-act" onClick="invokeAction(\'deleteEvent\',\'{{node.id}}\',\'{{node.__typename}}\')">\n        <i class="fa fa-trash" title="delete event"></i>\n    </span>\n</div>\n',
        EndDate: '<div>{{#if EndDate}}{{getdateTime EndDate}}{{/if}}</div>',
        StartDate:
          '<div>{{#if StartDate}}{{getdateTime StartDate}}{{/if}}</div>',
        VisitingCard0: 'EventMangment_Card_View',
        Title:
          '<div onclick="invokeAction(\'goToDetails\', this)" businessType="{{BusinessType}}" data-action="edit" data-bind="ID={{id}}" style="cursor: pointer;color: #1a73e8;"> {{Title}} </div>',
      },
      decorator: {
        Attachment: '',
        LinkedinURL: '',
      },
    },
    views: {
      'Seat Layout': {
        Default: 'true',
        DataSource: {
          FormID: 'AddSeatMap',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Parent key field': '',
          'Sharepoint Action': 'Add',
          Type: 'Form',
          URL: 'Event',
        },
        Query: '',
        Visible: false,
        FilterRule: '{ "where": {} }',
        Title: 'Seat Layout',
        Fields: {
          Title: {
            displayOrder: 2,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Status: {
            displayOrder: 2,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Type: {
            displayOrder: 3,
            caption: 'Type',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          TemplateName: {
            displayOrder: 4,
            caption: 'TemplateName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdBy: {
            displayOrder: 5,
            caption: 'createdBy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdDate: {
            displayOrder: 1,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        type: 'Form',
        DefaultSort: 'createdDate DESC',
      },
      Invite: {
        Default: 'true',
        DataSource: {
          FormID: 'InviteDetailsForm',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Parent key field': '',
          'Sharepoint Action': 'Edit',
          Type: 'Form',
          URL: 'Event',
        },
        Query: '',
        Visible: false,
        FilterRule: '{ "where": {} }',
        Title: 'Invite',
        Fields: {
          Title: {
            displayOrder: 1,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Status: {
            displayOrder: 2,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Type: {
            displayOrder: 3,
            caption: 'Type',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          TemplateName: {
            displayOrder: 4,
            caption: 'TemplateName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdBy: {
            displayOrder: 5,
            caption: 'createdBy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdDate: {
            displayOrder: 6,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        type: 'Form',
        DefaultSort: 'createdDate DESC',
      },
      Invites: {
        Default: 'true',
        DataSource: {
          FormID: 'InviteHistoryDetailsForm',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Parent key field': '',
          'Sharepoint Action': 'Add',
          Type: 'Form',
          URL: 'Event',
        },
        Query: '',
        Visible: false,
        FilterRule: '{ "where": {} }',
        Title: 'Invites',
        Fields: {
          Title: {
            displayOrder: 2,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Status: {
            displayOrder: 2,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Type: {
            displayOrder: 3,
            caption: 'Type',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          TemplateName: {
            displayOrder: 4,
            caption: 'TemplateName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdBy: {
            displayOrder: 5,
            caption: 'createdBy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdDate: {
            displayOrder: 1,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        type: 'Form',
        DefaultSort: 'createdDate DESC',
      },
      Past: {
        Actions: {
          'Embeded Actions': '',
          'General Actions': [],
          'Selected Item Action': [],
        },
        binding: {
          tod: 'moment.utc().format()',
        },
        Fields: {
          '_VenueAddress.PostalCode': {
            displayOrder: 10,
            caption: 'Postal Code',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          '_VenueAddress.State': {
            displayOrder: 9,
            caption: 'State',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '140px',
          },
          Privacy: {
            displayOrder: 4,
            caption: 'Privacy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          EndDate: {
            displayOrder: 3,
            caption: 'EndDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          '_VenueAddress.Country': {
            displayOrder: 11,
            caption: 'Country',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          StartDate: {
            displayOrder: 2,
            caption: 'Start Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          Currency: {
            displayOrder: 12,
            caption: 'Currency',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          '_VenueAddress.City': {
            displayOrder: 8,
            caption: 'City',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          createdDate: {
            displayOrder: 13,
            caption: 'created Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          Title: {
            displayOrder: 1,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          Tags: {
            displayOrder: 5,
            caption: 'Tags',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          VenueName: {
            displayOrder: 6,
            caption: 'Venue Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          '_VenueAddress.AddressLine': {
            displayOrder: 7,
            caption: 'Address Line',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        FilterRule: '{ "where":{ "and":[{"EndDate":{"lte":"@tod"}}]} }',
        'List Name': 'Event',
        QueryType: 'axios',
        Query:
          'query ($filters: JSON, $where: JSON) { Event { EventFind(filter: $filters) { edges { node { SeatReservation Privacy BusinessType EndDate ShowRemainingTickets StartDate Currency CancellationPolicy MaxNoRegistrations EventCountdown Title Timezone Tags Project MinDaysCancelling VenueName id LegalEntity Description IsOnlineEvent createdDate createdBy modifiedDate modifiedBy Images Logo Thumbnail _VenueAddress { Country PostalCode State City AddressLine id } } } } EventCount(where: $where) } }',
        Title: 'Past',
      },
      'Registration Types': {
        Default: 'true',
        DataSource: {
          FormID: 'RegistrationTypesDetailsForm',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Parent key field': '',
          'Sharepoint Action': 'Add',
          Type: 'Form',
          URL: 'Event',
        },
        Query: '',
        Visible: false,
        FilterRule: '{ "where": {} }',
        Title: 'Registration Types',
        Fields: {
          Title: {
            displayOrder: 2,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Status: {
            displayOrder: 2,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Type: {
            displayOrder: 3,
            caption: 'Type',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          TemplateName: {
            displayOrder: 4,
            caption: 'TemplateName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdBy: {
            displayOrder: 5,
            caption: 'createdBy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdDate: {
            displayOrder: 1,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        type: 'Form',
        DefaultSort: 'createdDate DESC',
      },
      'Live and Draft Events': {
        Default: true,
        QueryType: 'axios',
        binding: {
          tod: 'moment.utc().format()',
        },
        Query:
          'query ($filters: JSON, $where: JSON) { Event { EventFind(filter: $filters) { edges { node { StartDate Images BusinessType Title Timezone Tags Duration VenueName id LegalEntity Status createdDate createdBy modifiedDate Logo Thumbnail _VenueAddress { Country PostalCode State City AddressLine id } } } } EventCount(where: $where) } }',
        UI: {
          'List View Template': 'Live_Draft_Event',
          Pagination: 'pagingwithpage',
        },
        FilterRule:
          '{"where":{"or":[{"and":[{"or":[{"StartDate":{"lte":"@tod"}},{"StartDate":{"gte":"@tod"}},{"StartDate":{"exists":false}}, { "StartDate": null }]},{"or":[{"StartDate":{"gte":"@tod"}},{"StartDate":{"exists":false}}, { "StartDate": null }]}]},{"Status":"Not ready"}]}}',
        Title: 'Live and Draft Events',
        Fields: {
          '_VenueAddress.PostalCode': {
            displayOrder: 10,
            caption: '_VenueAddress.PostalCode',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          '_VenueAddress.State': {
            displayOrder: 9,
            caption: '_VenueAddress.State',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '140px',
          },
          Privacy: {
            displayOrder: 4,
            caption: 'Privacy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          EndDate: {
            displayOrder: 3,
            caption: 'EndDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          '_VenueAddress.Country': {
            displayOrder: 11,
            caption: '_VenueAddress.Country',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          StartDate: {
            displayOrder: 2,
            caption: 'StartDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          Currency: {
            displayOrder: 12,
            caption: 'Currency',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          '_VenueAddress.City': {
            displayOrder: 8,
            caption: '_VenueAddress.City',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          createdDate: {
            displayOrder: 13,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          Title: {
            displayOrder: 1,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          Tags: {
            displayOrder: 5,
            caption: 'Tags',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          VenueName: {
            displayOrder: 6,
            caption: 'VenueName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          '_VenueAddress.AddressLine': {
            displayOrder: 7,
            caption: '_VenueAddress.AddressLine',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        type: 'List',
        DefaultSort: 'createdDate DESC',
      },
      Schedule: {
        Default: 'true',
        DataSource: {
          FormID: 'SessionSlots',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Parent key field': '',
          'Sharepoint Action': 'Add',
          Type: 'Form',
          URL: 'Event',
        },
        Query: '',
        Visible: false,
        FilterRule: '{ "where": {} }',
        Title: 'Schedule',
        Fields: {
          Title: {
            displayOrder: 2,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Status: {
            displayOrder: 2,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Type: {
            displayOrder: 3,
            caption: 'Type',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          TemplateName: {
            displayOrder: 4,
            caption: 'TemplateName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdBy: {
            displayOrder: 5,
            caption: 'createdBy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdDate: {
            displayOrder: 1,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        type: 'Form',
        DefaultSort: 'createdDate DESC',
      },
      'Recurring Event': {
        Fields: {
          '_VenueAddress.PostalCode': {
            displayOrder: 10,
            caption: '_VenueAddress.PostalCode',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          '_VenueAddress.State': {
            displayOrder: 9,
            caption: '_VenueAddress.State',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '140px',
          },
          Privacy: {
            displayOrder: 4,
            caption: 'Privacy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          EndDate: {
            displayOrder: 3,
            caption: 'EndDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          '_VenueAddress.Country': {
            displayOrder: 11,
            caption: '_VenueAddress.Country',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          StartDate: {
            displayOrder: 2,
            caption: 'StartDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          Currency: {
            displayOrder: 12,
            caption: 'Currency',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          '_VenueAddress.City': {
            displayOrder: 8,
            caption: '_VenueAddress.City',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          createdDate: {
            displayOrder: 13,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          Title: {
            displayOrder: 1,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          Tags: {
            displayOrder: 5,
            caption: 'Tags',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          VenueName: {
            displayOrder: 6,
            caption: 'VenueName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          '_VenueAddress.AddressLine': {
            displayOrder: 7,
            caption: '_VenueAddress.AddressLine',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        DataSource: {
          FormID: 'AppointmentsDetailsForm',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Parent key field': '',
          'Sharepoint Action': 'Edit',
          Type: 'Form',
          URL: 'Event',
        },
        type: 'Form',
        QueryType: 'axios',
        Query: '',
        Visible: false,
        Title: 'Recurring Event',
      },
      'All Events': {
        fields: {
          '_VenueAddress.PostalCode': {
            displayOrder: 10,
            caption: 'Postal Code',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '160px',
            filterEnable: true,
            hidden: false,
            editable: true,
            type: 'number',
          },
          '_VenueAddress.State': {
            displayOrder: 9,
            caption: 'State',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '140px',
            type: 'string',
          },
          Privacy: {
            displayOrder: 4,
            caption: 'Privacy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          EndDate: {
            displayOrder: 3,
            caption: 'EndDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'date',
          },
          '_VenueAddress.Country': {
            displayOrder: 11,
            caption: 'Country',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          StartDate: {
            displayOrder: 2,
            caption: 'Start Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'date',
          },
          Currency: {
            displayOrder: 12,
            caption: 'Currency',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          '_VenueAddress.City': {
            displayOrder: 8,
            caption: 'City',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          createdDate: {
            displayOrder: 13,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '160px',
            type: 'date',
          },
          Title: {
            displayOrder: 1,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          Tags: {
            displayOrder: 5,
            caption: 'Tags',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'array',
          },
          VenueName: {
            displayOrder: 6,
            caption: 'Venue',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
          '_VenueAddress.AddressLine': {
            displayOrder: 7,
            caption: 'Address',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
        },
        inlineEditing: true,
        DdialogEditing: true,
        Query: '',
        QueryType: 'axios',
        Title: 'All Events',
        dataSource: {
          query: eventList,
          filter: {
            where: {
              or: [
                {
                  and: [
                    {
                      or: [
                        { StartDate: { lte: new Date() } },
                        { StartDate: { gte: new Date() } },
                        { StartDate: { exists: false } },
                        { StartDate: null },
                        // { userId: }
                      ],
                    },
                    {
                      or: [
                        { StartDate: { gte: new Date() } },
                        {
                          StartDate: {
                            exists: false,
                          },
                        },
                        {
                          StartDate: null,
                        },
                      ],
                    },
                  ],
                },
                {
                  Status: 'Not ready',
                },
              ],
            },
          },
          defaultSort: 'createdDate DESC',
        },
      },
      Event: {
        Fields: {
          '_VenueAddress.PostalCode': {
            displayOrder: 10,
            caption: '_VenueAddress.PostalCode',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          '_VenueAddress.State': {
            displayOrder: 9,
            caption: '_VenueAddress.State',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '140px',
          },
          Privacy: {
            displayOrder: 4,
            caption: 'Privacy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          EndDate: {
            displayOrder: 3,
            caption: 'EndDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          '_VenueAddress.Country': {
            displayOrder: 11,
            caption: '_VenueAddress.Country',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          StartDate: {
            displayOrder: 2,
            caption: 'StartDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          Currency: {
            displayOrder: 12,
            caption: 'Currency',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          Duration: {
            displayOrder: 9,
            caption: 'Duration',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          '_VenueAddress.City': {
            displayOrder: 8,
            caption: '_VenueAddress.City',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          createdDate: {
            displayOrder: 13,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          Title: {
            displayOrder: 1,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          Tags: {
            displayOrder: 5,
            caption: 'Tags',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          VenueName: {
            displayOrder: 6,
            caption: 'VenueName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          '_VenueAddress.AddressLine': {
            displayOrder: 7,
            caption: '_VenueAddress.AddressLine',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        DataSource: {
          FormID: 'EventDetailsForm',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Parent key field': '',
          'Sharepoint Action': 'Edit',
          Type: 'Form',
          URL: 'Event',
        },
        type: 'Form',
        QueryType: 'axios',
        Query: '',
        Visible: false,
        Title: 'Event',
      },
      'Not Available': {
        Default: 'true',
        DataSource: {
          FormID: 'NotAvailableSession',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Parent key field': '',
          'Sharepoint Action': 'Add',
          Type: 'Form',
          URL: 'Event',
        },
        Query: '',
        Visible: false,
        FilterRule: '{ "where": {} }',
        Title: 'Not Available',
        Fields: {
          Title: {
            displayOrder: 2,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Status: {
            displayOrder: 2,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Type: {
            displayOrder: 3,
            caption: 'Type',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          TemplateName: {
            displayOrder: 4,
            caption: 'TemplateName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdBy: {
            displayOrder: 5,
            caption: 'createdBy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdDate: {
            displayOrder: 1,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        type: 'Form',
        DefaultSort: 'createdDate DESC',
      },
      Calendar: {
        calendarFields: {
          Event: {
            Description: 'Title',
            End: 'EndDate',
            Start: 'StartDate',
          },
        },
        UI: {
          'Calendar View Template': 'calendarEvent',
        },
        Fields: [
          'Title',
          'StartDate',
          'EndDate',
          'Privacy',
          'Tags',
          'VenueName',
          'Currency',
          'createdDate',
        ],
        Query:
          'query($filters: JSON,$where: JSON) {\n  Event {\n    EventFind(filter: $filters) {\n      edges {\n        node {\n          id\n          StartDate\n          EndDate\n          Title\n          Tags\n          VenueName\n          Currency\n          createdDate\n          Privacy\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    EventCount(where:$where)\n    __typename\n  }\n}\n',
        Title: 'Calendar',
        type: 'Calander',
        isFilter: false,
      },
      Integrations: {
        Default: 'true',
        DataSource: {
          FormID: 'IntegrationsDetailsForm',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Parent key field': '',
          'Sharepoint Action': 'Add',
          Type: 'Form',
          URL: 'Event',
        },
        Query: '',
        Visible: false,
        FilterRule: '{ "where": {} }',
        Title: 'Integrations',
        Fields: {
          Title: {
            displayOrder: 2,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Status: {
            displayOrder: 2,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          Type: {
            displayOrder: 3,
            caption: 'Type',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          TemplateName: {
            displayOrder: 4,
            caption: 'TemplateName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdBy: {
            displayOrder: 5,
            caption: 'createdBy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          createdDate: {
            displayOrder: 1,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
        },
        type: 'Form',
        DefaultSort: 'createdDate DESC',
      },
      'my-events': {
        fields: {
          '_VenueAddress.PostalCode': {
            displayOrder: 10,
            caption: 'Postal Code',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '160px',
            filterEnable: true,
            hidden: false,
            editable: true,
            type: 'number',
          },
          '_VenueAddress.State': {
            displayOrder: 9,
            caption: 'State',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '140px',
            type: 'string',
          },
          Privacy: {
            displayOrder: 4,
            caption: 'Privacy',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          EndDate: {
            displayOrder: 3,
            caption: 'EndDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'date',
          },
          '_VenueAddress.Country': {
            displayOrder: 11,
            caption: 'Country',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          StartDate: {
            displayOrder: 2,
            caption: 'Start Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'date',
          },
          Currency: {
            displayOrder: 12,
            caption: 'Currency',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          '_VenueAddress.City': {
            displayOrder: 8,
            caption: 'City',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          createdDate: {
            displayOrder: 13,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '160px',
            type: 'date',
          },
          Title: {
            displayOrder: 1,
            caption: 'Title',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          Tags: {
            displayOrder: 5,
            caption: 'Tags',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'array',
          },
          VenueName: {
            displayOrder: 6,
            caption: 'Venue',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
          '_VenueAddress.AddressLine': {
            displayOrder: 7,
            caption: 'Address',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
        },
        inlineEditing: true,
        DdialogEditing: true,
        Title: 'My Events',
        dataSource: {
          query: eventList,
          filter: {
            where: {
              or: [
                {
                  createdBy: ctx.$auth.$state.user.data.email,
                },
              ],
            },
          },
          defaultSort: 'createdDate DESC',
        },
      },
    },
  },
  Registrations: {
    actions: {
      'Embeded Actions': '',
      'General Actions': ['Create Registration'],
      'Selected Item Action': [],
    },
    child: {},
    dataSource: {
      FormID: 'EventsAdvSearch',
      'Key Field': '',
      'Parent key field': '',
      Type: 'List',
      URL: 'Registration',
    },
    general: {
      caption: 'Registrations',
      name: 'Registration',
    },
    permissions: {
      Groups: '',
    },
    ui: {
      MobileViewTemplate: {
        isActive: true,
        templateName: 'Event_Registation_Mobile',
      },
      TemplateActions: {},
      Checkbox: 'True',
      'Card View Template': 'VisitingCard0',
      Width: '50%',
      Height: '',
      TemplateHelpers: {},
      'Display Order': '',
      'Map View Template': '',
      'List View Template': '',
      'Detail View': 'tab',
      Column: '',
      'Tile View': 'now',
      'App Type': 'View',
      Templates: {
        VisitingCard0: 'Registrations_Card_View',
        Status:
          '<div title="{{Status}}"><style>.reg-status {\n                  font-size: 10px;\n                            display: inline-block;\n                            color: #fff;\n                            margin-right: 5px;\n                            margin-bottom: 0px;\n                            padding: 3px 10px !important;\n                            border-radius: 20px !important;\n                            text-transform: capitalize;\n                        }\n                      .reg-success {\n                                      background-color: #0cb14b;\n                    }\n                      .reg-fail {\n                                      background-color: #f25955;\n                    }\n                      .reg-refund {\n                                      background-color: #3fa5ff;\n                    }\n                    .reg-parefund {\n                                      background-color: #b9b9b9;\n                    }\n                      .reg-parrefund {\n                                      background-color: #f4b400;\n                    }</style><div class="reg-status {{getStatusColor Status}}"> {{getCapitalResult Status}} </div></div>',
        SyncStatus:
          '<div><i class="{{ShowSyncField SFRegistrationId}}" style="{{getColor SFRegistrationId}}" onclick="invokeAction(\'changeSyncStatus\',this)" node={{node.id}}> </i></div>',
        CheckIn:
          '<style>\n    .checkin-btn {\ncolor: #fff;\npadding: 3px 10px !important;\n    background-color: #3fa5ff !important;;\nfont-size: 12px;\nborder-radius: 2px;\ncursor: pointer;\n}\n.check-label {\n        color: #1a73e8;\nfont-size: 13px;\n}\n</style>\n{{#ifStatus Status}}\n<div title="CheckIn">\n    {{#if CheckIn}}<span class="check-label">\n        <i class="fa fa-check" style="color: #1a73e8;margin-top:3px;" node={{node.id}}> </i>Checked in </span>\n    <span class="check-label">{{date_diff CheckIn}}</span>\n    {{else}}\n    <span onclick="invokeAction(\'CheckIn\',this)" class="checkin-btn">Check in</span>\n    {{/if}}\n</div>\n{{else}} <div style="height: 100%;" title=""></div>{{/ifStatus}}',
        FullName:
          '<div onclick="invokeAction(\'goToDetails\', this)" data-action="edit" data-bind="ID={{id}}" style="cursor: pointer;color: #1a73e8;"> {{FullName}} </div>',
      },
      decorator: {
        Attachment: '',
        LinkedinURL: '',
      },
    },
    views: {
      Registrations: {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: false,
          hideSearch: true,
        },
        default: true,
        fields: {
          EventName: {
            displayOrder: 6,
            caption: 'EventName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
          PaymentMethod: {
            displayOrder: 10,
            caption: 'PaymentMethod',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          CompanyName: {
            displayOrder: 4,
            caption: 'Organization',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          Phone: {
            displayOrder: 5,
            caption: 'Phone',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
            type: 'string',
          },
          Status: {
            displayOrder: 9,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
            type: 'lookup',
            dataSource: {
              query: registrationStatusOptions,
              itemText: 'value',
              itemValue: 'key',
              filter: { type: 'RegistrationStatus' },
            },
            // template: {
            //   name: 'issue-grid',
            //   params: {
            //     // eslint-disable-next-line no-template-curly-in-string
            //     route: '/event',
            //   },
            // },
            // items: [
            //   {
            //     text: 'Success Payment',
            //     value: 'Success',
            //   },
            //   {
            //     text: 'Pending Payment',
            //     value: 'Pending',
            //   },
            // ],
          },
          RegistrationId: {
            displayOrder: 6,
            caption: 'RegistrationId',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            inlineEdit: false,
            newForm: false,
            editForm: false,
          },
          createdDate: {
            displayOrder: 11,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
            inlineEdit: false,
            newForm: true,
            editForm: false,
          },
          TicketQuantity: {
            displayOrder: 9,
            caption: 'Attendees',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'number',
          },
          FullName: {
            displayOrder: 2,
            caption: 'Full Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
            inlineEdit: false,
            newForm: false,
            editForm: false,
          },
          TotalAmount: {
            displayOrder: 8,
            caption: 'TotalAmount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'number',
          },
          Email: {
            displayOrder: 3,
            caption: 'Email',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          action: {
            displayOrder: 11,
            caption: 'Action',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '130px',
            type: 'action',
            inlineEdit: false,
            newForm: false,
            editForm: false,
            condtion: ({ item, items, index }) => {
              return true
            },
          },
          FirstName: {
            displayOrder: 2,
            caption: 'First Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
            hidden: true,
            inlineEdit: true,
            newForm: true,
            editForm: false,
          },
        },
        template: {
          name: 'link-grid',
          context: {
            basePath: '/event',
          },
        },
        dataSource: {
          query: registrationList,
          defaultSort: 'createdDate DESC',
          type: 'graphql',
          model: 'Registration',
          // newItem: ,
        },
        title: 'Registrations',
        type: 'list',
        // type: 'card',
        // type: 'calendar',
        // type: 'path',
        // path: '/event-dashboard/abc'
      },
      'abandoned-registrations': {
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: false,
          hideSearch: false,
        },
        fields: {
          EventName: {
            displayOrder: 6,
            caption: 'EventName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
          PaymentMethod: {
            displayOrder: 10,
            caption: 'PaymentMethod',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          CompanyName: {
            displayOrder: 4,
            caption: 'Organization',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
          },
          Phone: {
            displayOrder: 5,
            caption: 'Phone',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
            type: 'string',
          },
          Status: {
            displayOrder: 9,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
            type: 'lookup',
            dataSource: {
              query: registrationStatusOptions,
              itemText: 'value',
              itemValue: 'key',
              filter: { type: 'RegistrationStatus' },
            },
            // template: {
            //   name: 'issue-grid',
            //   params: {
            //     // eslint-disable-next-line no-template-curly-in-string
            //     route: '/event',
            //   },
            // },
            // items: [
            //   {
            //     text: 'Success Payment',
            //     value: 'Success',
            //   },
            //   {
            //     text: 'Pending Payment',
            //     value: 'Pending',
            //   },
            // ],
          },
          RegistrationId: {
            displayOrder: 6,
            caption: 'RegistrationId',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
            inlineEdit: false,
            newForm: false,
            editForm: false,
          },
          createdDate: {
            displayOrder: 11,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'date',
            inlineEdit: false,
            newForm: true,
            editForm: false,
          },
          TicketQuantity: {
            displayOrder: 9,
            caption: 'Attendees',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'number',
          },
          FullName: {
            displayOrder: 2,
            caption: 'Full Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
            inlineEdit: false,
            newForm: false,
            editForm: false,
          },
          TotalAmount: {
            displayOrder: 8,
            caption: 'TotalAmount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'number',
          },
          Email: {
            displayOrder: 3,
            caption: 'Email',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            type: 'string',
          },
          action: {
            displayOrder: 11,
            caption: 'Action',
            searchEnable: false,
            sortEnable: false,
            columnWidth: '130px',
            type: 'action',
            inlineEdit: false,
            newForm: false,
            editForm: false,
            condtion: ({ item, items, index }) => {
              return true
            },
          },
          FirstName: {
            displayOrder: 2,
            caption: 'First Name',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
            type: 'string',
            hidden: true,
            inlineEdit: true,
            newForm: true,
            editForm: false,
          },
        },
        template: {
          name: 'link-grid',
          context: {
            basePath: '/event',
          },
        },
        dataSource: {
          query: registrationList,
          defaultSort: 'createdDate DESC',
          type: 'graphql',
          filter: {
            where: { Status: 'Failed' },
          },
          model: 'Registration',
          // newItem: ,
        },
        title: 'Abandoned Registrations',
        type: 'list',
        // type: 'card',
        // type: 'calendar',
        // type: 'path',
        // path: '/event-dashboard/abc'
      },
      Registration: {
        DefaultSort: 'createdDate DESC',
        DataSource: {
          FormID: 'RegistrationDetailForm',
          Aggregation: '',
          'Default view': '',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Key Field': '',
          'Sharepoint Action': 'Edit',
          Type: 'Form',
          URL: 'OfferCode',
        },
        Fields: {
          LastName: {
            displayOrder: 3,
            caption: 'LastName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          EventName: {
            displayOrder: 6,
            caption: 'EventName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
          },
          PaymentMethod: {
            displayOrder: 10,
            caption: 'PaymentMethod',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          Phone: {
            displayOrder: 5,
            caption: 'Phone',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          Status: {
            displayOrder: 9,
            caption: 'Status',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          RegistrationId: {
            displayOrder: 1,
            caption: 'RegistrationId',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          createdDate: {
            displayOrder: 11,
            caption: 'createdDate',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          TicketQuantity: {
            displayOrder: 7,
            caption: 'TicketQuantity',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
          FirstName: {
            displayOrder: 2,
            caption: 'FirstName',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '150px',
          },
          TotalAmount: {
            displayOrder: 8,
            caption: 'TotalAmount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '100px',
          },
          Email: {
            displayOrder: 4,
            caption: 'Email',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
          },
        },
        Query: '',
        visible: false,
        type: 'Form',
        title: 'Registration',
      },
    },
  },

  DiscountCodes: {
    actions: {
      'Embeded Actions': '',
      'General Actions': ['Create Registration'],
      'Selected Item Action': [],
    },
    child: {},
    dataSource: {
      FormID: 'EventsAdvSearch',
      'Key Field': '',
      'Parent key field': '',
      Type: 'List',
      URL: 'Offercode',
    },
    general: {
      caption: 'OfferCodes',
      name: 'OfferCode',
    },
    permissions: {
      Groups: '',
    },
    ui: {
      MobileViewTemplate: {
        isActive: true,
        templateName: 'Event_Registation_Mobile',
      },
      TemplateActions: {},
      Checkbox: 'True',
      'Card View Template': 'VisitingCard0',
      Width: '50%',
      Height: '',
      TemplateHelpers: {},
      'Display Order': '',
      'Map View Template': '',
      'List View Template': '',
      'Detail View': 'tab',
      Column: '',
      'Tile View': 'now',
      'App Type': 'View',
      Templates: {
        VisitingCard0: 'Registrations_Card_View',
        Status:
          '<div title="{{Status}}"><style>.reg-status {\n                  font-size: 10px;\n                            display: inline-block;\n                            color: #fff;\n                            margin-right: 5px;\n                            margin-bottom: 0px;\n                            padding: 3px 10px !important;\n                            border-radius: 20px !important;\n                            text-transform: capitalize;\n                        }\n                      .reg-success {\n                                      background-color: #0cb14b;\n                    }\n                      .reg-fail {\n                                      background-color: #f25955;\n                    }\n                      .reg-refund {\n                                      background-color: #3fa5ff;\n                    }\n                    .reg-parefund {\n                                      background-color: #b9b9b9;\n                    }\n                      .reg-parrefund {\n                                      background-color: #f4b400;\n                    }</style><div class="reg-status {{getStatusColor Status}}"> {{getCapitalResult Status}} </div></div>',
        SyncStatus:
          '<div><i class="{{ShowSyncField SFRegistrationId}}" style="{{getColor SFRegistrationId}}" onclick="invokeAction(\'changeSyncStatus\',this)" node={{node.id}}> </i></div>',
        CheckIn:
          '<style>\n    .checkin-btn {\ncolor: #fff;\npadding: 3px 10px !important;\n    background-color: #3fa5ff !important;;\nfont-size: 12px;\nborder-radius: 2px;\ncursor: pointer;\n}\n.check-label {\n        color: #1a73e8;\nfont-size: 13px;\n}\n</style>\n{{#ifStatus Status}}\n<div title="CheckIn">\n    {{#if CheckIn}}<span class="check-label">\n        <i class="fa fa-check" style="color: #1a73e8;margin-top:3px;" node={{node.id}}> </i>Checked in </span>\n    <span class="check-label">{{date_diff CheckIn}}</span>\n    {{else}}\n    <span onclick="invokeAction(\'CheckIn\',this)" class="checkin-btn">Check in</span>\n    {{/if}}\n</div>\n{{else}} <div style="height: 100%;" title=""></div>{{/ifStatus}}',
        FullName:
          '<div onclick="invokeAction(\'goToDetails\', this)" data-action="edit" data-bind="ID={{id}}" style="cursor: pointer;color: #1a73e8;"> {{FullName}} </div>',
      },
      decorator: {
        Attachment: '',
        LinkedinURL: '',
      },
    },
    views: {
      'Discount Codes': {
        default: true,
        defaultSort: 'createdDate DESC',
        fields: {
          currentUsageCount: {
            displayOrder: 9,
            caption: 'Current Usage Count',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '220px',
            type: 'number',
          },
          codeTitle: {
            displayOrder: 1,
            caption: 'Code',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'string',
          },
          isActive: {
            displayOrder: 4,
            caption: 'Active',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '120px',
            // type: 'string',
          },
          validTill: {
            displayOrder: 7,
            caption: 'Valid Till',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            type: 'date',
          },
          maxUsageCount: {
            displayOrder: 8,
            caption: 'Max Usage Count',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '180px',
            // type: 'number',
          },
          offerValue: {
            displayOrder: 5,
            caption: 'Offer Value',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            // type: 'string',
          },
          minApplicableOrderAmount: {
            displayOrder: 6,
            caption: 'Min Applicable Amount',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '220px',
            // type: 'number',
          },
          createdDate: {
            displayOrder: 10,
            caption: 'Created Date',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '250px',
            type: 'date',
          },
          isPercent: {
            displayOrder: 3,
            caption: 'Percent',
            searchEnable: true,
            sortEnable: true,
            columnWidth: '130px',
            // type: 'string',
          },
        },
        template: {
          name: 'discount-grid',
          context: {
            basePath: '/DiscountCodes',
          },
        },
        dataSource: {
          query: discountCodes, // getItems('users'),
          filter: {
            limit: '10',
            order: 'createdDate DESC',
            skip: '0',
            where: {},
          },
          defaultSort: 'createdDate DESC',
          type: 'graphql',
          // newItem: ,
        },
        ui: {
          hideDefaultHeader: false,
          hideDefaultFooter: false,
          showExpand: false,
          singleExpand: false,
          showSelect: true,
          hideFilter: true,
          hideSearch: false,
        },
        title: 'Discount Codes',
        model: 'OfferCode',
      },
      'Discount Code': {
        DefaultSort: 'createdDate DESC',
        DataSource: {
          FormID: 'EventDiscountCodes',
          Aggregation: '',
          'Default view': '',
          Params: {
            id: {
              type: 'string',
              mapwith: 'id',
            },
          },
          'Key Field': '',
          'Sharepoint Action': 'Edit',
          Type: 'Form',
          URL: 'OfferCode',
        },
        Fields: [
          'codeTitle',
          'description',
          'isPercent',
          'isActive',
          'offerValue',
          'minApplicableOrderAmount',
          'validTill',
          'createdAt',
          'maxUsageCount',
          'applicableOn',
          'currentUsageCount',
        ],
        Query: '',
        Visible: false,
        type: 'Form',
        Title: 'Discount Code',
      },
    },
  },
})
