import businessUnit from '../gql/businessUnit.gql'
import generalConfiguration from '~/config/apps/event/gql/registrationStatusOptions.gql'
import contactList from '~/config/apps/event/gql/contact.gql'
import crmActivity from '~/config/apps/event/gql/eventTasks.gql'
import { getCustomData } from '~/config/apps/event/rest'

export default {
  views: {
    organizationBusinessUnit: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: false,
        hideFilter: false,
        hideSearch: true,
      },
      itemTitle: 'Common.BusinessUnits',
      default: false,
      fields: {
        Name: {
          form: {
            caption: 'Common.NameRequired',
            displayOrder: 1,
          },
          displayOrder: 2,
          caption: 'Common.Name',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
          cssClasses: 'col-12 col-md-12',
          newForm: true,
          editForm: true,
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.NameRequired')
            },
          ],
        },
        Description: {
          form: {
            caption: 'Common.Description',
            displayOrder: 2,
          },
          displayOrder: 3,
          caption: 'Common.Description',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'richtext',
          cssClasses: 'col-12 col-md-12',
          hidden: true,
          newForm: true,
          editForm: true,
        },
        'child.Name': {
          displayOrder: 3,
          caption: 'Common.ParentBu',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
          newForm: false,
          editForm: false,
        },
        'contacts.FullName': {
          displayOrder: 3,
          caption: 'Common.PrimaryContact',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
          newForm: false,
          editForm: false,
        },
        '_CurrentAddress.AddressLine': {
          form: {
            caption: 'Common.AddressRequired',
            displayOrder: 3,
          },
          displayOrder: 5,
          caption: 'Common.AddressLine',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '160px',
          type: 'string',
          cssClasses: 'col-12 col-md-12',
          newForm: true,
          editForm: true,
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.AddressRequired')
            },
          ],
        },
        '_CurrentAddress.Country': {
          form: {
            caption: 'Common.Country',
            displayOrder: 6,
          },
          displayOrder: 6,
          caption: 'Common.Country',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          cssClasses: 'col-6 col-md-6',
          newForm: true,
          editForm: true,
        },
        '_CurrentAddress.City': {
          form: {
            caption: 'Common.City',
            displayOrder: 4,
          },
          displayOrder: 6,
          caption: 'Common.City',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          cssClasses: 'col-6 col-md-6',
          newForm: true,
          editForm: true,
        },
        '_CurrentAddress.State': {
          form: {
            caption: 'Common.State',
            displayOrder: 5,
          },
          displayOrder: 6,
          caption: 'Common.State',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          cssClasses: 'col-6 col-md-6',
          newForm: true,
          editForm: true,
        },
        '_CurrentAddress.PostalCode': {
          form: {
            caption: 'Common.ZipCode',
            displayOrder: 7,
          },
          displayOrder: 7,
          caption: 'Common.ZipCode',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          hidden: true,
          cssClasses: 'col-6 col-md-6',
          newForm: true,
          editForm: true,
        },
        Email: {
          form: {
            caption: 'Common.EmailCaption',
            displayOrder: 9,
          },
          displayOrder: 7,
          caption: 'Common.EmailCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          cssClasses: 'col-6 col-md-6',
          newForm: true,
          editForm: true,
        },
        Phone: {
          form: {
            caption: 'Common.Phone',
            displayOrder: 8,
          },
          displayOrder: 8,
          caption: 'Common.Phone',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
          cssClasses: 'col-6 col-md-6',
          newForm: true,
          editForm: true,
        },
        Type: {
          form: {
            caption: 'Common.Type',
            displayOrder: 10,
          },
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'lookup',
          cssClasses: 'col-6 col-md-6',
          hidden: true,
          inlineEdit: true,
          newForm: true,
          editForm: true,
          rules: [
            function (v) {
              return !!v || this.$t('Messages.Error.TypeSelected')
            },
          ],
          dataSource: {
            query: generalConfiguration,
            itemText: 'value',
            itemValue: 'key',
            filter(data) {
              return {
                type: 'BusinessTypeLocation',
              }
            },
          },
        },
        ParentId: {
          form: {
            caption: 'Common.ParentBusinessUnit',
            displayOrder: 11,
          },
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'lookup',
          cssClasses: 'col-6 col-md-6',
          hidden: true,
          inlineEdit: true,
          newForm: true,
          editForm: true,
          dataSource: {
            query: businessUnit,
            itemText: 'Name',
            itemValue: 'id',
          },
        },
        PrimeContactId: {
          form: {
            caption: 'Common.Contact',
            displayOrder: 12,
          },
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'lookup',
          cssClasses: 'col-6 col-md-6',
          hidden: true,
          inlineEdit: true,
          newForm: true,
          editForm: true,
          dataSource: {
            query: contactList,
            itemText: 'FullName',
            itemValue: 'id',
          },
        },
        Default: {
          displayOrder: 9,
          caption: 'Common.Default',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
          newForm: false,
          editForm: false,
        },
        Action: {
          displayOrder: 10,
          caption: 'Drawer.Action',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
          newForm: false,
          editForm: false,
        },
      },
      template: {
        name: 'organizationBussinessUnit-grid',
        context: {
          basePath: '/organization',
        },
      },
      dataSource: {
        query: businessUnit,
        defaultSort: 'createdDate DESC',
        type: 'graphql',
        model: 'Location',
        filter(ctx) {
          return {
            where: {},
          }
        },
      },
      title: 'organizationBusinessUnit',
      type: 'list',
    },
    organizationProductSubscription: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: false,
        hideFilter: false,
        hideSearch: true,
      },
      default: false,
      fields: {
        'SubProduct.DisplayName': {
          displayOrder: 2,
          caption: 'Common.Product',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '200px',
          type: 'string',
        },
        StartDate: {
          displayOrder: 3,
          caption: 'Common.StartDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'datetime',
        },
        EndDate: {
          displayOrder: 4,
          caption: 'Common.EndDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'datetime',
        },
        Cost: {
          displayOrder: 5,
          caption: 'Common.HeaderPrice',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
        },
        Unit: {
          displayOrder: 6,
          caption: 'Common.Unit',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '120px',
          type: 'string',
        },
        isActive: {
          displayOrder: 7,
          caption: 'Common.Active',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '120px',
          type: 'string',
        },
        AutoRenew: {
          displayOrder: 8,
          caption: 'Common.AutoRenew',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
        },
      },
      template: {
        name: 'organizationSubscription-grid',
        context: {
          basePath: '/organization',
        },
        actions: {
          new: {
            hidden: true,
          },
          edit: {
            hidden: true,
          },
          delete: {
            hidden: true,
          },
        },
      },
      dataSource: {
        type: 'rest',
        getData: (ctx) => getCustomData(`OrganizationInfos/getSubscription`),
      },
      title: 'organizationProductSubscription',
      type: 'list',
    },
    organizationTasks: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: false,
        hideSearch: true,
      },
      default: false,
      fields: {
        Title: {
          displayOrder: 2,
          caption: 'Common.TitleCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Status: {
          displayOrder: 3,
          caption: 'Common.Status',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Action: {
          displayOrder: 4,
          caption: 'Common.WaitFor',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Category: {
          displayOrder: 5,
          caption: 'Common.Category',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Type: {
          displayOrder: 6,
          caption: 'Common.TypeCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        TemplateName: {
          displayOrder: 7,
          caption: 'Common.TemplateNameCaption',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        createdBy: {
          displayOrder: 8,
          caption: 'Common.CreatedBy',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        createdDate: {
          displayOrder: 9,
          caption: 'Common.CreatedDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'date',
        },
        DueDate: {
          displayOrder: 10,
          caption: 'Common.DueDate',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'datetime',
        },
      },
      template: {
        name: 'organizationTask-grid',
        context: {
          basePath: '/organization',
        },
      },
      dataSource: {
        query: crmActivity,
        type: 'graphql',
        model: 'CRMActivity',
        filter(ctx) {
          return {
            where: {
              Type: 'Template',
            },
          }
        },
      },
      title: 'Tasks',
      type: 'list',
    },
  },
}
