import businessUnit from '../gql/businessUnit.gql'
import { getData } from '~/config/apps/event/rest'

export default {
  views: {
    organizationBusinessUnit: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: false,
        hideSearch: true,
      },
      default: false,
      fields: {
        Name: {
          displayOrder: 2,
          caption: 'Name',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        'child.Name': {
          displayOrder: 3,
          caption: 'Parent BU',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        'contacts.FullName': {
          displayOrder: 3,
          caption: 'Primary Contact',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        '_CurrentAddress.AddressLine': {
          displayOrder: 5,
          caption: 'Address Line',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '160px',
          type: 'string',
        },
        '_CurrentAddress.Country': {
          displayOrder: 6,
          caption: 'Country',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
        },
        Email: {
          displayOrder: 7,
          caption: 'Email',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
        },
        Phone: {
          displayOrder: 8,
          caption: 'Phone',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
        },
      },
      template: {
        context: {
          basePath: '/organization',
        },
      },
      dataSource: {
        query: businessUnit,
        defaultSort: 'createdDate DESC',
        type: 'graphql',
        model: 'Location',
        filter(ctx) {
          return {
            where: {},
          }
        },
      },
      title: 'organizationBusinessUnit',
      type: 'list',
    },
    organizationProductSubscription: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: false,
        hideSearch: true,
      },
      default: false,
      fields: {
        'SubProduct.DisplayName': {
          displayOrder: 2,
          caption: 'Product',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '200px',
          type: 'string',
        },
        StartDate: {
          displayOrder: 3,
          caption: 'Start Date',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'datetime',
        },
        EndDate: {
          displayOrder: 4,
          caption: 'End Date',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'datetime',
        },
        Cost: {
          displayOrder: 5,
          caption: 'Price',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '130px',
          type: 'string',
        },
        Unit: {
          displayOrder: 6,
          caption: 'Unit',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '120px',
          type: 'string',
        },
        isActive: {
          displayOrder: 7,
          caption: 'Active',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '120px',
          type: 'string',
        },
        AutoRenew: {
          displayOrder: 8,
          caption: 'Auto Renew',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '150px',
          type: 'string',
        },
      },
      template: {
        context: {
          basePath: '/organization',
        },
      },
      dataSource: {
        type: 'rest',
        getData: (ctx) => getData(`/OrganizationInfos/getSubscription`),
      },
      title: 'organizationProductSubscription',
      type: 'list',
    },
    organizationTasks: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: false,
        hideSearch: true,
      },
      default: false,
      fields: {
        Title: {
          displayOrder: 2,
          caption: 'Title',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Status: {
          displayOrder: 3,
          caption: 'Status',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Action: {
          displayOrder: 4,
          caption: 'Wait For',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Category: {
          displayOrder: 5,
          caption: 'Category',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Type: {
          displayOrder: 6,
          caption: 'Type',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        TemplateName: {
          displayOrder: 7,
          caption: 'Template Name',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        createdBy: {
          displayOrder: 8,
          caption: 'Created By',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'datetime',
        },
        createdDate: {
          displayOrder: 9,
          caption: 'Created Date',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'datetime',
        },
        DueDate: {
          displayOrder: 10,
          caption: 'Due Date',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'datetime',
        },
      },
      template: {
        context: {
          basePath: '/organization',
        },
      },
      dataSource: {
        type: 'rest',
        getData: (ctx) =>
          getData(`/CRMACTIVITIES?filter={"where":{"Type":"Template"}}`),
      },
      title: 'organizationProductSubscription',
      type: 'list',
    },
    organizationIntegration: {
      ui: {
        hideDefaultHeader: false,
        hideDefaultFooter: false,
        showExpand: false,
        singleExpand: false,
        showSelect: true,
        hideFilter: false,
        hideSearch: true,
      },
      default: false,
      fields: {
        'MetaData.Category': {
          displayOrder: 2,
          caption: 'Category',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        ServiceId: {
          displayOrder: 3,
          caption: 'App Name',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Status: {
          displayOrder: 4,
          caption: 'Status',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
        Action: {
          displayOrder: 5,
          caption: 'Action',
          searchEnable: true,
          sortEnable: true,
          columnWidth: '180px',
          type: 'string',
        },
      },
      template: {
        context: {
          basePath: '/organization',
        },
      },
      dataSource: {
        type: 'rest',
        getData: (ctx) => getData(`/OrganizationInfos/getMyConnections`),
      },
      title: 'organizationIntegration',
      type: 'list',
    },
  },
}
